package seedu.duke.exception;

/**
 * Enumeration of all the types of DukeException.
 */
public enum DukeExceptionType {
    UNKNOWN_INPUT,
    INVALID_MODE,
    WRITE_FILE_ERROR,
    ERROR_LOADING_FILE,

    INVALID_ADD_BOOKMARK_INPUT,
    EMPTY_DESCRIPTION,
    NON_INTEGER_INPUT,
    BOOKMARK_NUMBER_OUT_OF_BOUNDS,
    EMPTY_COMMAND,
    INVALID_URL,
    ERROR_LAUNCHING_URL,

    INVALID_ADD_SLOT,
    INVALID_COMMAND_FORMAT,
    INVALID_SLOT_NUMBER,
    INVALID_TIME_FORMAT,
    INVALID_SLOT_INPUT,
    INVALID_TIMETABLE_DAY,
    EMPTY_TIMETABLE
}