package seedu.duke.exception;

/**
 * Enumeration of all the types of DukeException.
 */
public enum DukeExceptionType {
    EMPTY_DESCRIPTION,
    INVALID_TASK_FORMAT,
    FULL_TASK_LIST,
    UNKNOWN_INPUT,
    INVALID_BOOKMARK_NUMBER,
    INVALID_SLOT_NUMBER,
    WRITE_FILE_ERROR,
    ERROR_LOADING_FILE,
    ERROR_LAUNCHING_URL,
    INVALID_URL,
    INVALID_BOOKMARK_INPUT,
    INVALID_TIME_FORMAT,
    INVALID_SLOT_INPUT,
    INVALID_MODE,
    INVALID_TIMETABLE_DAY,
    EMPTY_TIMETABLE
}