@startuml
autoactivate on
actor User
scale 1094 width

skinparam shadowing false
skinparam sequence {
    ActorBorderColor white
    
    ActorBackgroundColor white
    ActorFontColor white
    ActorFontSize 17
    ActorFontName ""
}

box "Data Tracker" #LightYellow
participant ":ManualTracker" as manualTracker <<class>>
endBox

box "Logic" #LightBlue
participant "handler:CreateLedgerHandler"
participant ":ParamChecker"
endBox

box "Data" #LightGreen
participant ":ledger:Ledger"
participant "ledger:LedgerList"
endBox

User-> manualTracker: Create Ledger

manualTracker ->manualTracker: handleCreateLedger()

   manualTracker-> "handler:CreateLedgerHandler" : getInstance()
    return handler

   manualTracker-> "handler:CreateLedgerHandler" : handlePacket(packet)

        create ":ledger:Ledger"
        "handler:CreateLedgerHandler" -> ":ledger:Ledger" : Ledger()
        return
        == Handling of Params in packet ==
        "handler:CreateLedgerHandler" -> "handler:CreateLedgerHandler" : handleParams(packet)
            "handler:CreateLedgerHandler" -> ":ParamChecker" : setPacket(packet)
            return
            loop For all paramType in the command packet
                note left: "Note: Params will be verified for correctness\nby ParamChecker singleton class before being\nset into the ledger instance."
                "handler:CreateLedgerHandler" -> "handler:CreateLedgerHandler" : handleSingleParam(packet, paramType)
                    alt "paramType = PARAM_DATE"
                        "handler:CreateLedgerHandler" ->":ParamChecker": checkAndReturnDate(paramType)
                        return date
                        "handler:CreateLedgerHandler" -> ":ledger:Ledger" : setDate(date)
                        return
                    end
                return
            end
        return
   return
   == Retrieval of newly created ledger from the command instance ==
   manualTracker-> "handler:CreateLedgerHandler" : getCurrLedger()
   return ledger
   == Storing of ledger into ledgerList ==
   manualTracker-> "ledger:LedgerList" : addItem(ledger)
    return
return state
return


@enduml