package seedu.zoomaster.exception;

/**
 * Enumeration of all the types of DukeException.
 */
public enum ZoomasterExceptionType {
    UNKNOWN_INPUT,
    UNKNOWN_HELP_COMMAND,
    INVALID_MODE,
    WRITE_FILE_ERROR,
    ERROR_LOADING_FILE,
    INVALID_ADD_BOOKMARK_INPUT,
    EMPTY_DESCRIPTION,
    EMPTY_COMMAND,
    NON_INTEGER_INPUT,
    ADD_SLOT_NON_INTEGER_INPUT,
    BOOKMARK_NUMBER_OUT_OF_BOUNDS,
    ZERO_SLOTS_IN_MODULE,
    INVALID_URL,
    ERROR_LAUNCHING_URL,
    INVALID_COMMAND_FORMAT,
    INVALID_MODULE,
    INVALID_SLOT_NUMBER,
    INVALID_TIME_FORMAT,
    INVALID_SLOT_INPUT,
    INVALID_TIMETABLE_DAY,
    EMPTY_TIMETABLE,
    CONNECTION_ERROR,
    JSON_PARSE_ERROR,
    EMPTY_FOLDER
}