@startuml
title __revisED's Add Maths Subject Sequence Diagram__\n

actor Bob
Bob -> Revised**: run()
activate Revised
Revised -> Ui++: printStart()
Ui --> Revised --
loop !exit program
Revised -> Ui ++ : readCommand()
Ui --> Revised --
Revised -> SubjectParser ++ : parse()
SubjectParser -> AddSubjectCommand**
activate AddSubjectCommand
AddSubjectCommand --> SubjectParser -- : AddSubjectCommand
SubjectParser --> Revised-- : AddSubjectCommand
Revised -> AddSubjectCommand ++ : execute()
alt new Subject
AddSubjectCommand -> Subject **
activate Subject
Subject --> AddSubjectCommand-- : Maths
AddSubjectCommand -> SubjectList++ : add()
SubjectList --> AddSubjectCommand--
AddSubjectCommand -> Ui ++: printSubject()
Ui --> AddSubjectCommand --
AddSubjectCommand --> Revised
else command not understood
AddSubjectCommand --> Revised  : NoSubjectException

else subject exists
AddSubjectCommand --> Revised -- : RepeatedSubjectException
end
end
@enduml