@startuml

title __revisED's Flashcard package Class Diagram__\n

abstract class Command {
    +isExit(): boolean
}

class FlashcardCommand {
    +execute(Topic): Flashcard
    +isExit(): boolean
}

Command <|-- FlashcardCommand

class AddFlashcardCommand {
    -fullCommand: String
    +execute(Topic): Flashcard
    +isExit(): boolean
}

FlashcardCommand <|-- AddFlashcardCommand

class DeleteFlashcardCommand {
    -fullCommand: String
    +execute(Topic): Flashcard
    +isExit(): boolean
}

FlashcardCommand <|-- DeleteFlashcardCommand

class ExitFlashcardCommand {
    +isExit(): boolean
}

FlashcardCommand <|-- ExitFlashcardCommand

class HelpFlashcardCommand {
    +execute(Topic): Flashcard
    +isExit(): boolean
}

FlashcardCommand <|-- HelpFlashcardCommand

class ListFlashcardCommand {
    +execute(Topic): Flashcard
    +isExit(): boolean
}

FlashcardCommand <|-- ListFlashcardCommand

class SorryFlashcardCommand {
    +execute(Topic): Flashcard
    +isExit(): boolean
}

FlashcardCommand <|-- SorryFlashcardCommand

@enduml