@startuml
title __revisED's Return Maths Subject Sequence Diagram__\n

actor Bob
Bob -> Revised ** : run()
activate Revised
Revised -> Ui ++ : printStart()
Ui --> Revised --
loop !exit program
Revised -> Ui ++ : readCommand()
Ui --> Revised --
Revised -> SubjectParser ++ : parse()
SubjectParser -> ReturnSubjectCommand **
activate ReturnSubjectCommand
ReturnSubjectCommand --> SubjectParser -- : ReturnSubjectCommand
SubjectParser --> Revised-- : ReturnSubjectCommand
Revised -> ReturnSubjectCommand ++ : execute()
ReturnSubjectCommand -> SubjectList ++
loop Subjects in SubjectList
opt subject title equals maths
SubjectList --> ReturnSubjectCommand : Maths
ReturnSubjectCommand --> Revised : Maths
end
SubjectList --> ReturnSubjectCommand --
end
ReturnSubjectCommand --> Revised -- : NoSubjectException
Revised -> ReturnSubjectCommand ++ : goToSubject()
ReturnSubjectCommand -> Ui ++ : printGoToSubject()
Ui --> ReturnSubjectCommand --
loop  !exit subject
ReturnSubjectCommand -> Ui ++ : readCommand
Ui --> ReturnSubjectCommand --
ReturnSubjectCommand -> TopicParser++ : parse
end
end
@enduml