@startuml

title __revisED's Topic package Class Diagram__\n

abstract class Command {
    +isExit(): boolean
}

class TopicCommand {
    +execute(TopicList): Topic
    +isExit(): boolean
}

Command <|-- TopicCommand

class AddTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- AddTopicCommand

class DeleteTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- DeleteTopicCommand

class ExitTopicCommand {
    +isExit(): boolean
}

TopicCommand <|-- ExitTopicCommand

class FindTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- FindTopicCommand

class HelpTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- HelpTopicCommand

class ListTopicCommand {
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- ListTopicCommand

class QuizTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- QuizTopicCommand

class ResultTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- ResultTopicCommand

class ReturnTopicCommand {
    -fullCommand: String
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- ReturnTopicCommand

class SorryTopicCommand {
    +execute(TopicList): Topic
    +isExit(): boolean
}

TopicCommand <|-- SorryTopicCommand

@enduml