@startuml

 -> ":CommandEventDel": execute()
activate ":CommandEventDel"
activate ":EventList"
activate ":EventList" #DarkSalmon
alt isInteger
    ":CommandEventDel" -> ":EventList" : deleteEvent()
    activate ":EventList"
    ":EventList" -> ":Event": remove()
    activate ":Event"
    return
    ":EventList" -> ":Event" : printEvent()
   activate ":Event"
    return output
    return output
    return output
else else
":CommandEventDel" -> ":EventList" : clearEvents()
 activate ":EventList"
 activate ":CommandEventDel"
 ":EventList" -> ":Event": clear()

 return
 return output
 deactivate ":EventList"
 return output
 deactivate ":CommandEventDel"
end
@enduml