@startuml
 -> CommandEventAdd: execute()


activate CommandEventAdd
CommandEventAdd -> EventList: addEvent()
activate EventList
EventList -> Event: add()
activate Event
return
EventList -> Event : printEvent()
activate Event
return
return
return
deactivate CommandEventAdd




@enduml