@startuml
 -> ":CommandViewEventAttendance": execute()

activate ":CommandViewEventAttendance"
":CommandViewEventAttendance" -> ":EventList" : listAttendance()
activate ":EventList"
":EventList" -> ":EventList" : checkEventExistence()
opt eventExists
    ":EventList" -> ":Event" : findEventByName()
    activate ":Event"
    return e
    ":EventList" -> ":Event" : printEventParticipant()
    activate ":Event"
    return output
    ":EventList" -> ":Event" : size()
    activate ":Event"
    return output
end

return output
deactivate ":EventList"
<-- ":CommandViewEventAttendance" : output
deactivate ":CommandViewEventAttendance"
@enduml