@startuml
 -> ":CommandSearchEvent" : execute()

activate ":CommandSearchEvent"

activate ":EventList"
":EventList" -> ":EventList" : checkIfEventNameMatch()
activate ":EventList"
return output
":EventList" -> ":EventList" : checkIfEventDateMatch()
activate ":EventList"
return output
":EventList" -> ":EventList" : printFilteredEvents()
activate ":EventList"
":EventList" -> ":Event" : printEvent()
activate ":Event"
":EventList" <-- ":Event"
deactivate ":Event"
return output
":CommandSearchEvent" <-- ":EventList" : output
deactivate ":EventList"
  <-- ":CommandSearchEvent" : output
deactivate ":CommandSearchEvent"
@enduml