@startuml
 -> ":CommandEventList" : execute()

activate ":CommandEventList"

":CommandEventList"  -> ":EventList":printEventList()
activate ":EventList" #DarkSalmon
alt empty ArrayList
    ":EventList" --> ":CommandEventList"
else else
    loop until end of ArrayList
        ":EventList" -> ":Event" : printEvent()
        activate ":Event"
        ":Event" --> ":EventList"
        deactivate ":Event"
        ":EventList" --> ":CommandEventList" : output
        deactivate ":EventList"
        return output
    end
    deactivate ":EventList"
    deactivate ":EventList"
    deactivate ":CommandEventList"
end
@enduml