@startuml
 -> CommandSearchEvent: execute()

activate CommandSearchEvent
activate EventList
activate EventList
CommandSearchEvent -> EventList:searchEvents()

EventList -> EventList : checkIfEventNameMatch() | checkIfEventDateMatch
activate EventList
EventList -> EventList : printFilteredEvents()
activate EventList
EventList -> Event : printEvent()
activate Event
EventList <-- Event
deactivate Event
return
return
CommandSearchEvent <-- EventList
deactivate EventList
return
deactivate CommandSearchEvent



@enduml