

@startuml

Package " "<<Square>>{
    Class Command
    Class CommandHelp
    Class CommandBye
    Class CommandFinanceSummary
    Class CommandFinanceAdd
    Class CommandFinanceDel
    Class CommandEventAdd
    Class CommandEventDel
    Class CommandEventList
    Class CommandSearchEvent
    Class CommandEventStatus
    Class CommandAddMember
    Class CommandChangeMemberInfo
    Class CommandDelMember
    Class CommandListConnection
    Class CommandListProfAdmin
    Class CommandSearchMember
    Class CommandViewMember
}

CommandHelp --|> Command
CommandBye --|> Command
CommandFinanceSummary --|> Command
CommandFinanceAdd --|> Command
CommandFinanceDel --|> Command
CommandEventAdd --> Command
CommandEventDel --|> Command
CommandEventList --|> Command
CommandSearchEvent --|> Command
CommandEventStatus --|> Command
CommandAddMember --|> Command
CommandChangeMemberInfo --|> Command
CommandDelMember --|> Command
CommandListConnection --|> Command
CommandListProfAdmin --|> Command
CommandSearchMember --|> Command
CommandViewMember --|> Command

@enduml