@startuml
autoactivate on

skinparam shadowing false
skinparam sequence {
ActorBorderColor white

ActorBackgroundColor white
ActorFontColor white
ActorFontSize 17
ActorFontName ""
}

actor User

User -> ":EntryTracker": Edit Entry

":EntryTracker" ->":EntryTracker": handleCreateEntry()
    == Phase 1: Retrieve Entry ==
   ":EntryTracker"-> "retrieveEntryHandler:RetrieveEntryHandler" : RetrieveEntryHandler.getInstance()
    return RetrieveEntryHandler.handler

       ":EntryTracker"-> "retrieveEntryHandler:RetrieveEntryHandler" : handlePacket

            create "entry:Entry"
            "retrieveEntryHandler:RetrieveEntryHandler" -> "entry:Entry" : Entry()
            return
            == Handling of Params in packet for retrieval ==
            "retrieveEntryHandler:RetrieveEntryHandler" -> "retrieveEntryHandler:RetrieveEntryHandler" : handleParams
                "retrieveEntryHandler:RetrieveEntryHandler" -> ":ParamChecker" : setPacket(packet)
                return
                loop For all paramType in the command packet
                    note left: "Note: The entry to be edited is first retrieved \nusing the retrieve command."
                    "retrieveEntryHandler:RetrieveEntryHandler" -> "retrieveEntryHandler:RetrieveEntryHandler" : handleSingleParam
                        alt "paramType = PARAM_INDEX"
                            "retrieveEntryHandler:RetrieveEntryHandler" ->":ParamChecker": checkAndReturnIndex(paramType, entryList)
                            return index
                            note left: "Note: Set index to modify at entry list\nso that the entry of interest can be retrieved via regular\ngetter methods from entrylist"
                            "retrieveEntryHandler:RetrieveEntryHandler" -> "entryList:EntryList" : setIndexToModify(index)
                            return
                        end
                    return
                end
            return
       return

    == Retrieval of entry from entryList ==
    ":EntryTracker" -> "entryList:EntryList" : getItemAtCurrIndex()
    return entry

    == Phase 2: Edit Entry ==
       ":EntryTracker"-> "editEntryHandler:EditEntryHandler" : EditEntryHandler.getInstance()
        return editEntryHandler.handler
        ":EntryTracker" -> "editEntryHandler:EditEntryHandler" : setPacket(packet)
        return
        ":EntryTracker" -> "editEntryHandler:EditEntryHandler" : handlePacket

        == Handling of Params in packet for edit ==
        "editEntryHandler:EditEntryHandler" -> "editEntryHandler:EditEntryHandler" : handleParams
            "editEntryHandler:EditEntryHandler" -> ":ParamChecker" : setPacket(packet)
            return
            loop For all paramType in the command packet
                note left: "Note: Params will be verified for correctness\nby ParamChecker singleton class before being\nset into the entry instance."
                "editEntryHandler:EditEntryHandler" -> "editEntryHandler:EditEntryHandler" : handleSingleParam
                    alt "paramType = PARAM_TIME"
                        "editEntryHandler:EditEntryHandler" ->":ParamChecker": checkAndReturnTime(paramType)
                        return time
                        "editEntryHandler:EditEntryHandler" -> "entry:Entry" : setTime(time)
                        return
                    else "paramType = PARAM_AMOUNT"
                        "editEntryHandler:EditEntryHandler" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        "editEntryHandler:EditEntryHandler" -> "entry:Entry" : setAmount(amount)
                        return
                    else "paramType = PARAM_INC"
                        "editEntryHandler:EditEntryHandler" -> "entry:Entry" : setEntryType(EntryType.INC)
                        return
                    else "paramType = PARAM_EXP"
                        "editEntryHandler:EditEntryHandler" -> "entry:Entry" : setEntryType(EntryType.EXP)
                        return
                    else "paramType = PARAM_DESCRIPTION"
                        "editEntryHandler:EditEntryHandler" -> "entry:Entry" : setDescription(description)
                        return
                    else "paramType = PARAM_CATEGORY"
                        "editEntryHandler:EditEntryHandler" ->":ParamChecker": checkAndReturnCategory(paramType)
                        return
                        "editEntryHandler:EditEntryHandler" -> "entry:Entry" : setCategory()
                        return
                    end
                return
            end
        return
   return
   == Edit successful ==
return state
return
box "Data Tracker" #LightYellow
participant ":EntryTracker"
endBox

box "Logic" #LightBlue
participant "retrieveEntryHandler:RetrieveEntryHandler"
participant "editEntryHandler:EditEntryHandler"
participant ":ParamChecker"
endBox

box "Data" #LightGreen
participant "entry:Entry"
participant "entryList:EntryList"
endBox
@enduml