@startuml
title When User Set an Expense Goal
actor User

User -> ":GoalTracker" : setExpenseGoal()
activate ":GoalTracker"

":GoalTracker" -> ":InputParser" : parseGoalCommand()
activate ":InputParser"
return newCommand

":GoalTracker" -> ":Goal" : Goal()
activate ":Goal"

":Goal" -> ":TotalGoalList" : addGoal()
activate ":TotalGoalList"

":TotalGoalList" -> ":Goal" : Goal being set

":Goal" -> ":GoalTracker" : Goal status updated

":GoalTracker" -> User : Goal Status displayed to user
deactivate ":GoalTracker"
@enduml