@startuml

abstract class Command

Class RouteMapCommand{
-busCode: String
+executeCommand(): void
-selectAndPrintBusRoute(: String) : void
-checkBusCode(: String): void
}
Class Parser{
+extractType(): Boolean
}
Class BusData {
+{static} selectBus (:String) : Bus
}
Class CustomException {
-exception: ExceptionType
}
Class Bus {
-busNumber : String
}
enum BusStops {
PGP
KENTRIDGEMRTSTATION
...
COLLEGEGREEN
PGPR
+{static}FindBusStop(: String) : BusStops
}
Class Ui {
+{static} printFullRoute(:Bus) :void
+{static} getCommand(): String
}

enum ExceptionType {
MISSING_BUS_CODE
INVALID_BUS
INVALID_COMMAND
...
}

Command <|--right RouteMapCommand
Parser "1"<--down RouteMapCommand
RouteMapCommand ..right> BusData
BusData --> "*" Bus
Bus ..> BusStops
RouteMapCommand ..> CustomException :throws
Parser ..> CustomException :throws
RouteMapCommand ..> Ui

CustomException -> ExceptionType


@enduml