@startuml
actor User


User -> ":NuSchedule" ++ : add
":NuSchedule" -> ":Parser" ++ : parse()
":Parser" --> ":NuSchedule" -- : parsed command
":NuSchedule" -> ":AddCommand" ++ : execute()
":AddCommand" -> ":EventList" ++ : addEvent()
":EventList" --> ":AddCommand" -- : event
":AddCommand" -> ":UI" ++ : printMessage()
":UI" --> ":AddCommand" -- : message
":AddCommand" --> ":NuSchedule" -- : return

deactivate ":NuSchedule"
@enduml