@startuml
hide footbox

participant ":NotUS" as NotUS
participant ":ParseAddEventCommand" as ParseAddEventCommand
participant ":AddEventCommand" as AddEventCommand
participant ":Formatter" as Formatter
participant ":Timetable" as Timetable

activate NotUS

create AddEventCommand
activate ParseAddEventCommand

ParseAddEventCommand -> AddEventCommand: <<create>>

activate AddEventCommand
AddEventCommand --> NotUS
deactivate AddEventCommand

deactivate ParseAddEventCommand

NotUS -> AddEventCommand: setData()

activate AddEventCommand
AddEventCommand --> NotUS
deactivate AddEventCommand

NotUS -> NotUS: executeCommand()

destroy ParseAddEventCommand
activate NotUS
NotUS -> AddEventCommand: execute()

activate AddEventCommand
alt eventEndBeforeStarting
AddEventCommand -> Formatter: formatEventString()
activate Formatter
return
deactivate Formatter
AddEventCommand --> NotUS: result
end

AddEventCommand -> Timetable: getClashingEvents()
activate Timetable
return
deactivate Timetable

AddEventCommand -> Timetable: addEvent()
activate Timetable
return
deactivate Timetable

AddEventCommand -> StorageManager: saveTimetable()
activate StorageManager
return
deactivate StorageManager

AddEventCommand -> Formatter: formatEventString()
activate Formatter
return
deactivate Formatter

AddEventCommand --> NotUS: result
deactivate AddEventCommand

deactivate NotUS
destroy AddEventCommand
@enduml