@startuml

activate NotUS

create AddNoteCommand

ParseAddNoteCommand -> AddNoteCommand: <<create>>

activate AddNoteCommand
AddNoteCommand --> NotUS
deactivate AddNoteCommand

deactivate ParseAddNoteCommand

destroy ParseAddNoteCommand

NotUS -> Command: setData()

activate Command
Command --> NotUS
deactivate Command

NotUS -> NotUS: executeCommand()
activate NotUS
NotUS -> AddNoteCommand: execute()

activate AddNoteCommand
AddNoteCommand -> Parser: inputContent()
activate Parser
return

deactivate Parser
AddNoteCommand -> TagManager: rebindTags()
activate TagManager
return
deactivate TagManager

AddNoteCommand -> Notebook: addNote()
activate Notebook
return
deactivate Notebook

AddNoteCommand -> StorageManager: saveNote()
activate StorageManager
return
deactivate StorageManager

AddNoteCommand -> Formatter: formatNote()
activate Formatter
return
deactivate Formatter

AddNoteCommand --> NotUS: result
deactivate AddNoteCommand

deactivate Notus

@enduml