@startuml

Package " "<<Rectangle>>{
    Class StorageManager
    Class InterfaceManager
    Class Notebook
    Class Timetable
    Class TagManager
    Class ParserManager
    Class Command
    Class Notus
}

Notus --> StorageManager
Notus --> InterfaceManager
Notus --> Notebook
Notus --> Timetable
Notus --> TagManager
Notus --> ParserManager
Notus --> Command

ParserManager --> Command

Command --> Notebook
Command --> Timetable
Command --> TagManager
Command --> StorageManager

@enduml