@startuml

Package " "<<Rectangle>>{
    Class Command
    Class ExitCommand
    Class AddEventCommand
    Class AddNoteCommand
    Class CreateTagCommand
    Class DeleteNoteCommand
    Class DeleteTagCommand
    Class EditEventCommand
    Class EditNoteCommand
    Class HelpCommand
    Class FindCommand
    Class ListEventCommand
    Class ListNoteCommand
    Class ListTagCommand
    Class PinCommand
    Class RemindCommand
    Class TagCommand
    Class ViewNoteCommand
    Class ArchiveNoteCommand
    Class UnarchiveNoteCommand
}

ExitCommand --|> Command 
AddEventCommand --|> Command 
AddNoteCommand --|> Command 
ArchiveNoteCommand --|> Command 
CreateTagCommand --|> Command 
DeleteNoteCommand --|> Command 
DeleteTagCommand --|> Command 
EditEventCommand --|> Command 
EditNoteCommand --|> Command 
FindCommand --|> Command 
HelpCommand --|> Command 
ListEventCommand --|> Command 
ListNoteCommand --|> Command 
ListTagCommand --|> Command
PinCommand --|> Command 
RemindCommand --|> Command 
TagCommand --|> Command 
UnarchiveNoteCommand --|> Command 
ViewNoteCommand --|> Command 

@enduml