@startuml

actor User
participant ":Ui" as Ui
participant ":Logic" as Logic
participant ":TaskMap" as TaskMap
participant ":Storage" as Storage
participant ":Main" as Main

'delete
activate Main

Main -> Storage: loadTasks()
activate Storage

'Storage --> Storage: createDirectory()
'activate Storage
'
'Storage --> Storage
'deactivate Storage
'
'Storage --> Storage: readTasksFromFile()
'activate Storage
'
'Storage --> Storage
'deactivate Storage

Storage --> Main
deactivate Storage

User -> Ui: "delete 2173"
activate Ui

Ui -> Logic: processRaw("delete 2173")
activate Logic

Logic -> TaskMap: remove(2173)
activate TaskMap

TaskMap --> Logic
deactivate TaskMap

Logic --> Ui
deactivate Logic

Ui --> User
deactivate Ui

'bye
User -> Ui: "bye"
activate Ui

Ui -> Logic: processRaw("bye")
activate Logic

Logic --> Ui
deactivate Logic

Ui --> User
deactivate Ui

Main -> Storage: writeTasksToFile()
activate Storage

Storage --> Main
deactivate Storage

deactivate Main

@enduml