@startuml
skinparam Shadowing false

participant ":Fitr"
participant "<<class>>\n:Parser"
participant ":HelpCommand"

activate ":Fitr"
":Fitr" -> "<<class>>\n:Ui" : read()
activate "<<class>>\n:Ui"
":Fitr" <-- "<<class>>\n:Ui"
deactivate "<<class>>\n:Ui"

":Fitr" -> "<<class>>\n:Parser" : parse("help")
activate "<<class>>\n:Parser"
create ":HelpCommand"
"<<class>>\n:Parser" -> ":HelpCommand" ++
return
":Fitr" <-- "<<class>>\n:Parser"
deactivate "<<class>>\n:Parser"


":Fitr" -> ":HelpCommand" : execute()
activate ":HelpCommand"
":HelpCommand" -> "<<class>>\n:Ui" : printHelpMessage()
activate "<<class>>\n:Ui"
return

":HelpCommand" --> ":Fitr"
deactivate ":HelpCommand"
'To position the delete symbol below activation bar
":HelpCommand" -[hidden]-> ":Fitr"
destroy ":HelpCommand"
deactivate ":Fitr"

hide footbox
@enduml
