@startuml

skinparam classAttributeIconSize 0
skinparam Shadowing false
skinparam MinClassWidth 75
skinparam packageStyle Rectangle

hide circle
hide empty members

skinparam Class {
    BorderThickness 1
    BorderColor #000000
}

class Fitr
class Food
class Exercise
class Calorie
class Parser
class EditCommandParser
class StorageManager
class XYZStorage

class ListManager
class ExerciseList
class FoodList
class GoalList

ExerciseList --> ListManager
FoodList --> ListManager
GoalList --> ListManager

abstract class "{abstract}\nCommand" as Command
class XYZCommand

Command <|-d- XYZCommand
note right of XYZCommand: AddExerciseCommand,\nDeleteCommand, etc.

Command -u-> Fitr

Parser -d-> Fitr
EditCommandParser -d-> Parser
Ui -d-> Fitr
StorageManager -> Fitr
ListManager -l-> Fitr

XYZStorage -> StorageManager
note left of XYZStorage: ExerciseStorage,\nFoodStorage, etc.

Food o-- FoodList
Exercise o-- ExerciseList
Goal o-- GoalList

Food -u- Calorie
Exercise -u- Calorie

@enduml
