@startuml

Note --|> TaggableObject
Notebook "1" o-- "*" Note
Note ..> Tag
TaggableObject }o== Tag

class Notebook {
-notes: <ArrayList<Note>
-archivedNotes: <ArrayList<Note>
+addNote(Note): Note
+getNote(int): Note
+getNote(String): boolean
+getNote(String, boolean): Note
+setNotes(int, Note): boolean
+getNoteIndex(Note): int
+getSize(): int
+findNotes(String): ArrayList<Note>
+deleteNote(int): boolean
+deleteNote(String): boolean
+checkPinned(): boolean
+getPinnedNotes(ArrayList<Note>): ArrayList<Note>
+getUnpinnedNotes(ArrayList<Note>): ArrayList<Note>
+getSortedList(Boolean, Boolean): ArrayList<Note>
+getSortedList(Boolean, Boolean, ArrayList<Note>): ArrayList<Note>
+archiveNotes(int): String
+archiveNotes(String): boolean
+unarchiveNotes(int): String
+unarchiveNotes(String): boolean
+getArchivedNoteSize(): int
}

class Note {
-title: String
-content: ArrayList<String>
-isPinned: Boolean
-isArchived: boolean
+getContentString(): String
+getPinnedString(): String
+togglePinned(): void
+toggleArchived(): void
+toSaveString(): String
}

abstract class TaggableObject {
-tags: ArrayList<Tag>
+getTagsName(): String
}

@enduml