@startuml
NotUS -> StorageManager: Load saved file
NotUS <-- StorageManager: Load result

loop !Exit Command
NotUS -> InterfaceManager: getUserCommandInput()
NotUS <-- InterfaceManager: userInput

NotUS -> Parser: parseCommand()
NotUS <-- Parser: new Command

NotUS -> Command: setData()
NotUS <-- Command
NotUS -> Command: execute()
NotUS <-- Command: execute result
NotUS -> InterfaceManager: prints()
NotUS <-- InterfaceManager

end

@enduml
