@startuml
Notus -> StorageManager: Load saved file
Notus <-- StorageManager: Load result

loop !Exit Command
Notus -> InterfaceManager: getUserCommandInput()
Notus <-- InterfaceManager: userInput

Notus -> ParserManager: parseCommand()
create Parser
ParserManager -> Parser: <<create>>

activate Parser
ParserManager <-- Parser
deactivate Parser

ParserManager -> Parser: parse()

activate Parser

create Command
Parser -> Command: <<create>>

activate Command
Notus <-- Command:
deactivate Command

deactivate Parser
destroy Parser

Notus -> Command: setData()

activate Command
Notus <-- Command
deactivate Command

Notus -> Command: execute()

activate Command
Command -> Formatter: formatString()
Command <-- Formatter: string
Notus <-- Command: string

deactivate Command

Notus -> InterfaceManager: prints()
Notus <-- InterfaceManager

destroy Command
end

@enduml
