@startuml
-> ParserManager: ParseCommand()

alt add-n
create ParseAddNoteCommand
ParserManager -> ParseAddNoteCommand: <<create>>

activate ParseAddNoteCommand
ParserManager <-- ParseAddNoteCommand
deactivate ParseAddNoteCommand

ParserManager -> ParseAddNoteCommand: parse()

activate ParseAddNoteCommand
create Command
ParseAddNoteCommand -> Command: <<create>>

activate Command
<-- Command:
deactivate Command

deactivate ParseAddNoteCommand
destroy ParseAddNoteCommand

else delete-n
create ParseDeleteNoteCommand
ParserManager -> ParseDeleteNoteCommand: <<create>>

activate ParseDeleteNoteCommand
ParserManager <-- ParseDeleteNoteCommand
deactivate ParseDeleteNoteCommand

ParserManager -> ParseDeleteNoteCommand: parse()

activate ParseDeleteNoteCommand
create Command
ParseDeleteNoteCommand -> Command: <<create>>

activate Command
<-- Command:
deactivate Command

deactivate ParseDeleteNoteCommand
destroy ParseDeleteNoteCommand

end

@enduml

@startuml

create ParserManager

create ParseAddNoteCommand
ParserManager -> ParseAddNoteCommand: <<create>>

activate ParseAddNoteCommand
ParserManager <-- ParseAddNoteCommand
deactivate ParseAddNoteCommand

ParserManager -> ParseAddNoteCommand: parse()
activate ParseAddNoteCommand

alt valid string
create AddNoteCommand
ParseAddNoteCommand -> AddNoteCommand: <<create>>

activate AddNoteCommand
ParseAddNoteCommand <-- AddNoteCommand
deactivate AddNoteCommand

ParserManager <-- ParseAddNoteCommand
<-- ParserManager

else invalid string
create IncorrectCommand
ParseAddNoteCommand -> IncorrectCommand: <<create>>

activate IncorrectCommand
ParseAddNoteCommand <-- IncorrectCommand
deactivate IncorrectCommand

ParserManager <-- ParseAddNoteCommand

deactivate ParseAddNoteCommand
destroy ParseAddNoteCommand

<-- ParserManager

end

@enduml