@startuml
create NotUS
create PinCommand
activate PinCommand

Parser -> PinCommand : PinCommand(index)
deactivate PinCommand

NotUS -> PinCommand: execute()
activate PinCommand 

alt PinByIndex

    PinCommand -> Notebook: getNotes()
    activate Notebook
    Notebook --> PinCommand: notes 
    deactivate Notebook

    PinCommand -> Note: get(index)
    activate Note
    Note --> PinCommand: note
    deactivate Note
  
else __
ref over PinCommand, Notebook, Note: get Note using title

end

alt note does not exist 

    PinCommand --> NotUS: Unsuccesful

else 

    PinCommand --> NotUS: note content + pinned status
    deactivate PinCommand

end

destroy PinCommand
@enduml