@startuml

hide footbox

participant ":NotUS" as NotUS
participant ":ParsePinCommand" as ParsePinCommand
participant ":PinCommand" as PinCommand
participant ":Notebook" as Notebook

participant ":Note" as Note

create NotUS
create ParsePinCommand

create PinCommand
activate PinCommand

ParsePinCommand -> PinCommand : <<create>>
deactivate PinCommand

NotUS -> PinCommand: execute()
activate PinCommand 

alt PinByIndex

    PinCommand -> Notebook: getNotes()
    activate Notebook
    Notebook --> PinCommand: notes 
    deactivate Notebook

    PinCommand -> Note: get(index)
    activate Note
    Note --> PinCommand: note
    deactivate Note
  
else __
ref over PinCommand, Notebook, Note: get Note using title

end

alt note does not exist 

    PinCommand --> NotUS: Unsuccesful

else 

    PinCommand --> NotUS: note content + pinned status
    deactivate PinCommand

end

destroy PinCommand
@enduml