@startuml
skinparam classAttributeIconSize 0
skinparam Shadowing false
skinparam MinClassWidth 75
skinparam packageStyle Folder

hide circle
hide empty members

skinparam Class {
    BorderThickness 1
    BorderColor #000000
}

class StorageManager
class ExerciseStorage
class FoodStorage
class GoalStorage
class TipStorage
class UserStorage

class FoodList
class ExerciseList
class GoalList

class Fitr
class User

class Food
class Exercise
class Goal

FoodList o-- "*" Food
ExerciseList o-- "*" Exercise
GoalList o-- "*" Goal

Fitr --> "1" StorageManager

StorageManager --> "1" ExerciseStorage
ExerciseStorage ..> ExerciseList

StorageManager --> "1" FoodStorage
FoodStorage ..> FoodList

StorageManager --> "1" GoalStorage
GoalStorage ..> GoalList
GoalStorage ..> ExerciseList
GoalStorage ..> FoodList
GoalStorage ..> User

StorageManager --> "1" UserStorage
UserStorage ..> User

StorageManager --> "1" TipStorage

@enduml
