@startuml


skinparam classAttributeIconSize 0
class Storage {
   -{static}{field} DIRECTORY_NAME: String="data"
   -{static}{field} FILE_NAME: String="data.json"
   -{static}{field} TIMETABLE: String = "nusmods_calendar.ics"
   +{method} loadTasks(): TaskMap
   +{method} writeTasksToFile(TaskMap)
   -{method} createFile(): Boolean
   -{method} readTasksFromFile(): TaskMap
}

class Gson {
    +{method} toJson(Task):String
    +{method} fromJson(String, Type): Task
}
class File
class FileWriter
class TaskMap
class Task

Storage -> Gson
Storage -[dashed]-> File
Storage -[dashed]-> FileWriter
Storage -[dashed]-> TaskMap
Storage -[dashed]-> Task

@enduml
