@startuml

hide circle
skinparam classAttributeIconSize 0

enum "<<Enumeration>> \n SystemException" {
EXCEPTION_INVALID_COMMAND
EXCEPTION_INVALID_PREFIX
EXCEPTION_MISSING_PREFIX
EXCEPTION_MISSING_MESSAGE_AFTER_COMMAND
EXCEPTION_MISSING_DESCRIPTION

EXCEPTION_MISSING_TITLE_PREFIX
EXCEPTION_MISSING_TITLE

EXCEPTION_MISSING_TIMING_PREFIX
EXCEPTION_MISSING_TIMING

EXCEPTION_MISSING_TAG_PREFIX
EXCEPTION_MISSING_TAG

EXCEPTION_MISSING_SORT
EXCEPTION_INVALID_SORT_TYPE

EXCEPTION_MISSING_INDEX_PREFIX
EXCEPTION_MISSING_INDEX
EXCEPTION_INVALID_INDEX_FORMAT
EXCEPTION_INVALID_INDEX_VALUE

EXCEPTION_MISSING_LINE_CONTENT
}

@enduml

@startuml

hide circle
skinparam classAttributeIconSize 0

enum "<<Enumeration>> \n SystemException" {
EXCEPTION_MISSING_PIN
EXCEPTION_MISSING_ARCHIVE

EXCEPTION_MISSING_KEYWORD

EXCEPTION_CONTENT_MISSING

EXCEPTION_INVALID_END_INPUT
EXCEPTION_INVALID_DEL_INPUT
EXCEPTION_INVALID_INPUT_FORMAT
EXCEPTION_CLASH_FORMAT

EXCEPTION_MISSING_RECURRING_END_TIME
EXCEPTION_EARLY_REMINDER
EXCEPTION_INVALID_TIMING_FORMAT
EXCEPTION_INVALID_LIST_TIMING_FORMAT
EXCEPTION_INVALID_REMINDER_FORMAT
EXCEPTION_SEARCH_DATE_OUT_OF_RANGE
EXCEPTION_MISSING_RECURRING_TYPE
EXCEPTION_INVALID_RECURRING_TYPE
EXCEPTION_INVALID_TIME_UNIT

EXCEPTION_FILE_CREATION_ERROR
EXCEPTION_FILE_NOT_FOUND_ERROR
EXCEPTION_FILE_DELETION_ERROR

}

@enduml