@startuml
participant ":Fitr" as Fitr
participant ":TipList" as TipList
participant ":StorageManager" as StorageManager
participant ":TipManager" as TipManager
participant ":Ui" as Ui <<class>>
activate Fitr
create TipList
Fitr -> TipList++
TipList -> StorageManager++ : loadTipList()
return tipList
deactivate StorageManager
TipList --> Fitr: tipList
deactivate TipList

create TipManager
Fitr -> TipManager++: tipList
return
Fitr -> TipManager++: execute()
TipManager -> TipManager++: getTip(totalNumberOfTips)
return tip
TipManager -> Ui++: printMessageInYellow(tip)
return
return
TipManager -[hidden]-> Fitr
destroy TipManager
destroy TipList
deactivate Fitr
hide footbox
@enduml