@startuml

class Ui
class InputStream
class OutputStream

skinparam classAttributeIconSize 0
abstract class DisplayDateStructure {
    #{field}screen: char[][]
    +{method} getScreen: char[][]
    #{method}{abstract} generateScreen(TaskMap)
}

class DayStructure {
    #{method} generateContent(TaskMap)
}

class WeekStructure {
    -{static}{field} DISPLAY_HEIGHT: int=11
    #{method} generateContent(TaskMap)
    -{method} generateScreenBorder()

}

class MonthStructure {
    -{static}{field} DISPLAY_HEIGHT: int=53
    -{static}{field} ROW_NUM_OFFSET: int=2
    #{method} generateContent(TaskMap)
    -{method} generateScreenBorder()
}

enum DisplayMode {
    ALL
    WEEK
    MONTH
    DAY
}

InputStream "1"<->"1" Ui
Ui "1"<->"1" OutputStream
Ui --> DisplayDateStructure
DisplayDateStructure -[dashed]-> DisplayMode
DisplayDateStructure <|-- DayStructure
DisplayDateStructure <|-- WeekStructure
DisplayDateStructure <|-- MonthStructure


@enduml