package seedu.duke.storage.name;

import seedu.duke.exceptions.nameexceptions.NameException;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Scanner;

public class NamesDB {
    private static java.nio.file.Path filePath;

    /**
     * Loads the database of names.
     * Creates a default list of names if database doesn't exist.
     **/
    public static void loadDB(ArrayList<String> nameList) throws NameException {
        String home = Paths.get("").toAbsolutePath().toString();
        try {
            Files.createDirectories(Paths.get(home, "data"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        filePath = Paths.get(home, "data", "Names.txt");
        nameList.clear();
        boolean isExistingDirectory = Files.exists(filePath);
        if (isExistingDirectory) {
            File f = new File(String.valueOf(filePath));
            Scanner scan;
            try {
                scan = new Scanner(f);
            } catch (FileNotFoundException e) {
                throw new NameException(" ☹ OOPS!!! Unable to find database.");
            }
            while (scan.hasNext()) {
                String nameToProcess = scan.nextLine();
                nameList.add(nameToProcess);
            }
        } else {
            File yourFile = new File(String.valueOf(filePath));
            try {
                boolean isSuccessful = yourFile.createNewFile();
                if (!isSuccessful) {
                    throw new NameException(" ☹ OOPS!!! Unable to create database.");
                } else {
                    nameList.add("Reiko Copher");
                    nameList.add("Kim Mushrush");
                    nameList.add("Rosalie Hux");
                    nameList.add("Kesha Barrio");
                    nameList.add("Eliana Upshaw");
                    nameList.add("Manuela Naff");
                    nameList.add("Colleen Eaglin");
                    nameList.add("Nerissa Masters");
                    nameList.add("Marlene Smullen");
                    nameList.add("Tasia Noren");
                    nameList.add("Caryn Bibee");
                    nameList.add("Kenisha Son");
                    nameList.add("Theresia Woody");
                    nameList.add("Chang Peterka");
                    nameList.add("Olive Juarbe");
                    nameList.add("Eneida Leisy");
                    nameList.add("Laurice Strozier");
                    nameList.add("Dianna Bleakley");
                    nameList.add("Joeann Harbaugh");
                    nameList.add("Jasmin Maupin");
                    nameList.add("Lawana Cocklin");
                    nameList.add("Meggan Stoddart");
                    nameList.add("Santos Therrien");
                    nameList.add("Peg Wendel");
                    nameList.add("Ian Begin");
                    nameList.add("Arianne Ruggerio");
                    nameList.add("Sharleen Carwile");
                    nameList.add("Taylor Demar");
                    nameList.add("Dortha Daly");
                    nameList.add("Coletta Jarrell");
                    nameList.add("Jovita Lawry");
                    nameList.add("Elliott Joiner");
                    nameList.add("Forrest Moylan");
                    nameList.add("Sammy Meriwether");
                    nameList.add("Emilee Hernadez");
                    nameList.add("Beatris Hodgin");
                    nameList.add("Danelle Randel");
                    nameList.add("Elijah Hebb");
                    nameList.add("Clint Riesgo");
                    nameList.add("Todd Edelman");
                    nameList.add("Ingrid Harley");
                    nameList.add("Linwood Hennig");
                    nameList.add("Caroll Berger");
                    nameList.add("Vertie Scalzo");
                    nameList.add("Cecily Aaronson");
                    nameList.add("Luis Groh");
                    nameList.add("Li Hymer");
                    nameList.add("Billie Salazar");
                    nameList.add("Hyun Lovern");
                    nameList.add("Barabara Geno");
                    nameList.add("Margaret Pickford");
                    nameList.add("Kelli Pollan");
                    nameList.add("Myron Tison");
                    nameList.add("Elvera Desjardin");
                    nameList.add("Lita Feinstein");
                    nameList.add("Carmel Mcloud");
                    nameList.add("Mickie Figaro");
                    nameList.add("Val Leitner");
                    nameList.add("Rolando Hamamoto");
                    nameList.add("Albertine Hogsett");
                    nameList.add("Julianne Agudelo");
                    nameList.add("Pamala Yamashiro");
                    nameList.add("Mohammad Teegarden");
                    nameList.add("Reena Kimpel");
                    nameList.add("Reed Carpenter");
                    nameList.add("Eusebia Jenson");
                    nameList.add("Rochelle Miramontes");
                    nameList.add("Desire Betty");
                    nameList.add("Cathi Dore");
                    nameList.add("Bradford Gouin");
                    nameList.add("Allyn Bibee");
                    nameList.add("Isabell Rockhill");
                    nameList.add("Domingo Matzke");
                    nameList.add("Josefina Clairmont");
                    nameList.add("Antonio Dunker");
                    nameList.add("Margarita Casa");
                    nameList.add("Daina Woodhouse");
                    nameList.add("Korey Balog");
                    nameList.add("Rosann Lapine");
                    nameList.add("Carlena Reuss");
                    nameList.add("Dianne Douglass");
                    nameList.add("Barabara Sporer");
                    nameList.add("Mellisa Diederich");
                    nameList.add("Charline Mcgaha");
                    nameList.add("Rebecca Necessary");
                    nameList.add("Antwan Reinoso");
                    nameList.add("Cindy Sachs");
                    nameList.add("Penney Collington");
                    nameList.add("Gaylord Featherstone");
                    nameList.add("Alanna Levin");
                    nameList.add("Stephan Sisneros");
                    nameList.add("Spencer Toner");
                    nameList.add("Kevin Woods");
                    nameList.add("Estell Iwamoto");
                    nameList.add("Gail Rapier");
                    nameList.add("Jeanice Keithley");
                    nameList.add("Amal Hargrove");
                    nameList.add("Geri Dicks");
                    nameList.add("Tien Matas");
                    nameList.add("Yuri Riemann");
                    nameList.add("Bianca Cornish");
                    nameList.add("Zainab Morley");
                    nameList.add("Molly Bouvet");
                    nameList.add("Angelo Blanchard");
                    nameList.add("Roberta Villarreal");
                    nameList.add("Rafi Davila");
                    nameList.add("Lilly-Rose Dougherty");
                    nameList.add("Mikaela Cairns");
                    nameList.add("Milli Doyle");
                    nameList.add("Billy Singh");
                    nameList.add("Catrin Rankin");
                    nameList.add("Armaan Harris");
                    nameList.add("Suzannah Orozco");
                    nameList.add("Charley Clements");
                    nameList.add("Natalya Rangel");
                    nameList.add("Osman Britton");
                    nameList.add("Petra Kidd");
                    nameList.add("Trent Griffiths");
                    nameList.add("Hajrah Timms");
                    nameList.add("Tonya Knowles");
                    nameList.add("Ellise Knox");
                    nameList.add("Sasha Bowden");
                    nameList.add("Teddie Mccaffrey");
                    nameList.add("Zuzanna Eastwood");
                    nameList.add("Hughie Kramer");
                    nameList.add("Amy-Louise Rigby");
                    nameList.add("Arian Frederick");
                    nameList.add("Tarik Burt");
                    nameList.add("Zayd Dennis");
                    nameList.add("Sydney Espinoza");
                    nameList.add("Jimmy Wardle");
                    nameList.add("Malak Hampton");
                    nameList.add("Rick England");
                    nameList.add("Elara Beasley");
                    nameList.add("Carolina Hayden");
                    nameList.add("Bailey Glass");
                    nameList.add("Irene Whyte");
                    nameList.add("Kloe Phillips");
                    nameList.add("Astrid Castro");
                    nameList.add("Hina John");
                    nameList.add("Desiree Chapman");
                    nameList.add("Shanay Plummer");
                    nameList.add("Kristy Whittaker");
                    nameList.add("Aaryan Burke");
                    nameList.add("Jazmine Bridges");
                    nameList.add("Kara Rodriquez");
                    nameList.add("Kajetan Colon");
                    nameList.add("Tyla Neal");
                    nameList.add("Selin Skinner");
                    nameList.add("Sofia Burns");
                    nameList.add("Arham Peralta");
                    nameList.add("Hazel Vaughn");
                    nameList.add("Gabriela Rosa");
                    nameList.add("Huda Rogers");
                    nameList.add("Arisha Snyder");
                    nameList.add("Carl Dolan");
                    nameList.add("Dean Jennings");
                    nameList.add("Iman Deacon");
                    nameList.add("Dawn Keenan");
                    nameList.add("Adina Fry");
                    nameList.add("Adrianna Boyle");
                    nameList.add("Suman Marquez");
                    nameList.add("Demi Foreman");
                    nameList.add("Poppy-Rose Aldred");
                    nameList.add("Sadia Rayner");
                    nameList.add("Yasir Walls");
                    nameList.add("Jakob Gibbons");
                    nameList.add("Bryson Huffman");
                    nameList.add("Yolanda Hoover");
                    nameList.add("Kurt Marsden");
                    nameList.add("Suhayb Burnett");
                    nameList.add("Andre Paul");
                    nameList.add("Donald Castaneda");
                    nameList.add("Denny Mueller");
                    nameList.add("Rickie Hawkins");
                    nameList.add("Summer-Rose Noel");
                    nameList.add("Rosanna Edmonds");
                    nameList.add("Shaquille Freeman");
                    nameList.add("Whitney Keith");
                    nameList.add("Owais Sawyer");
                    nameList.add("Mehdi Gough");
                    nameList.add("Gianni Kerr");
                    nameList.add("Jagoda Bains");
                    nameList.add("Kane Vargas");
                    nameList.add("Stacey Brookes");
                    nameList.add("Misty Watkins");
                    nameList.add("Danial Spooner");
                    nameList.add("Abid Cole");
                    nameList.add("Natasha Coates");
                    nameList.add("Parris Lin");
                    nameList.add("Mark Sutton");
                    nameList.add("Lorelei Carver");
                    nameList.add("Ronnie Reilly");
                    nameList.add("Toyah Stuart");
                    nameList.add("Aleisha Jenkins");
                    nameList.add("Sharmin Hurst");
                    nameList.add("Lucinda Kearns");
                    nameList.add("Josh Welch");
                    nameList.add("Sianna Kouma");
                    nameList.add("Pippa Morse");
                    nameList.add("Mira Dunne");
                    nameList.add("Daisy-Mae Cortes");
                    nameList.add("Ava Senior");
                    nameList.add("Addie Devine");
                    nameList.add("Savannah Oneill");
                    nameList.add("Anoushka Dunn");
                    nameList.add("Karam Frost");
                    nameList.add("Rudi Navarro");
                    nameList.add("Mckenzie Bowden");
                    nameList.add("Isadora Hogg");
                    nameList.add("Alma Haynes");
                    nameList.add("Perry Winter");
                    nameList.add("Eshaan Leblanc");
                    nameList.add("Darius Smyth");
                    nameList.add("Morwenna Wilcox");
                    nameList.add("John-James Ward");
                    nameList.add("Kaan Torres");
                    nameList.add("Gwion Fenton");
                    nameList.add("Darcie Ferry");
                    nameList.add("Destiny Mosley");
                    nameList.add("Sacha Hume");
                    nameList.add("Jaiden Kelly");
                    nameList.add("Tariq Peck");
                    nameList.add("Zeeshan Mcconnell");
                    nameList.add("Ella-Rose Harding");
                    nameList.add("Aleksandra Marquez");
                    nameList.add("Ann Hoffman");
                    nameList.add("Reilly Collins");
                    nameList.add("Allison Frye");
                    nameList.add("Kamil Mcgowan");
                    nameList.add("Wade Vega");
                    nameList.add("Bonnie Ramsay");
                    nameList.add("Leo Mccaffrey");
                    nameList.add("Leela Robson");
                    nameList.add("Ana Valentine");
                    nameList.add("Sid Robles");
                    nameList.add("Mert Rigby");
                    nameList.add("Bear Case");
                    nameList.add("Yusra Orozco");
                    nameList.add("Erica Browne");
                    nameList.add("Danish Brook");
                    nameList.add("Bobbie Ryan");
                    nameList.add("Alexandria Bailey");
                    nameList.add("Diane Melton");
                    nameList.add("Dexter Mejia");
                    nameList.add("Dennis Allan");
                    nameList.add("Khadeejah Ramirez");
                    nameList.add("Fahim Frey");
                    nameList.add("Shuaib Daly");
                    nameList.add("Angel Mccartney");
                    nameList.add("Aaliya Austin");
                    nameList.add("Silas Cameron");
                    nameList.add("Jake Wilkinson");
                    nameList.add("Borys Douglas");
                    nameList.add("Zoey Molina");
                    nameList.add("Ayub Owens");
                    nameList.add("Rayhan Cooley");
                    nameList.add("Renee Bain");
                    nameList.add("Ines Dunlop");
                    nameList.add("Davey Rich");
                    nameList.add("Izabela Odling");
                    nameList.add("Bradleigh Black");
                    nameList.add("Karter Craft");
                    nameList.add("Adelaide Legge");
                    nameList.add("Reon Villegas");
                    nameList.add("Coco Lutz");
                    nameList.add("Don Herring");
                    nameList.add("Corrina Hopper");
                    nameList.add("Shawn Clemons");
                    nameList.add("Asiya Chester");
                    nameList.add("Akash Dougherty");
                    nameList.add("Derry Young");
                    nameList.add("Carley Knott");
                    nameList.add("Elliott Singh");
                    nameList.add("Jozef Ventura");
                    nameList.add("Colby Stewart");
                    nameList.add("Priya Weiss");
                    nameList.add("Hussein Macgregor");
                    nameList.add("Adelle Little");
                    nameList.add("Kay Nelson");
                    nameList.add("Montell Stone");
                    nameList.add("Haleemah Sosa");
                    nameList.add("Candice Shepherd");
                    nameList.add("Rayhaan Neal");
                    nameList.add("Jeremiah Rasmussen");
                    nameList.add("Yasemin Dalton");
                    nameList.add("Collette Carr");
                    nameList.add("Kaine Bonner");
                    nameList.add("Liberty Roach");
                    nameList.add("Ian Cruz");
                    nameList.add("Matei Cook");
                    nameList.add("Arnav Dawson");
                    nameList.add("Jodie Amin");
                    nameList.add("Grant Sears");
                    nameList.add("Daisie Lindsey");
                    nameList.add("Patrycja Lopez");
                    nameList.add("Ophelia Braun");
                    nameList.add("Mali Keeling");
                    nameList.add("Tyron Snow");
                    nameList.add("Nabeel Bloggs");
                    nameList.add("Kornelia Larsen");
                    nameList.add("Ignacy Connor");
                    nameList.add("Theresa Melia");
                    nameList.add("Zahra Ramsay");
                    nameList.add("Alasdair Morrow");
                    nameList.add("Khadeejah Erickson");
                    nameList.add("Luisa Campos");
                    nameList.add("Ahsan Choi");
                    nameList.add("Lorelai Bains");
                    nameList.add("Samual Sadler");
                    nameList.add("Kush Price");
                    nameList.add("Mylah Kirkland");
                    nameList.add("Ari Mustafa");
                    nameList.add("Mohammad Power");
                    nameList.add("Adele Arroyo");
                    nameList.add("Pixie Holt");
                    nameList.add("Shyla Glass");
                    nameList.add("Clyde Wagstaff");
                    nameList.add("Gracie-Leigh Garcia");
                    nameList.add("Mehdi Schmidt");
                    nameList.add("Koa Broadhurst");
                    nameList.add("Neive Milner");
                    nameList.add("Chenai Bernal");
                    nameList.add("Kason Colley");
                    nameList.add("Avni Weber");
                    nameList.add("Phoebe Firth");
                    nameList.add("Aj Holder");
                    nameList.add("Ayah Kelley");
                    nameList.add("Candice Mcdougall");
                    nameList.add("Liam Kim");
                    nameList.add("Milton Stanley");
                    nameList.add("Glenda Woodcock");
                    nameList.add("Lilli Soto");
                    nameList.add("Mert Woodward");
                    nameList.add("Yanis Mccann");
                    nameList.add("Leonard Philip");
                    nameList.add("Dario Williamson");
                    nameList.add("Markus Rice");
                    nameList.add("Siya Haworth");
                    nameList.add("Zaynab Guthrie");
                    nameList.add("Paige Peck");
                    nameList.add("Lawson Hudson");
                    nameList.add("Coral Coates");
                    nameList.add("Umair Robin");
                    nameList.add("Ishaaq Tran");
                    nameList.add("Vickie Luna");
                    nameList.add("Daisy Farrell");
                    nameList.add("Muhammad Chaney");
                    nameList.add("Asha Hinton");
                    nameList.add("Zac Holcomb");
                    nameList.add("Bridie Ramirez");
                    nameList.add("Kaif Shields");
                    nameList.add("Sulaiman Walsh");
                    nameList.add("Ellie-Rose Murphy");
                    nameList.add("Alara Watkins");
                    nameList.add("Audrey Dupont");
                    nameList.add("Zayaan Faulkner");
                    nameList.add("Daniela Browning");
                    nameList.add("Riccardo Bostock");
                    nameList.add("Arfa Meyers");
                    nameList.add("Brenden Stout");
                    nameList.add("Aiesha Jordan");
                    nameList.add("Giles Martins");
                    nameList.add("Joshua Robins");
                    nameList.add("Rachel Reed");
                    nameList.add("Finnley Armitage");
                    nameList.add("Jon-Paul Lin");
                    nameList.add("Meg Edge");
                    nameList.add("Leyton Magana");
                    nameList.add("Jai Garner");
                    nameList.add("Shawn Heaton");
                    nameList.add("Samirah Pike");
                    nameList.add("Ioana Hartley");
                    nameList.add("Jorden Blevins");
                    nameList.add("Darla Kinney");
                    nameList.add("Erik Mcarthur");
                    nameList.add("Clifford Stubbs");
                    nameList.add("Bryson Jacobs");
                    nameList.add("Darren Gallegos");
                    nameList.add("Lillie Stein");
                    nameList.add("Randall Herrera");
                    nameList.add("Keaton Owen");
                    nameList.add("Nisha Lawrence");
                    nameList.add("Austin Hassan");
                    nameList.add("Ellis Huber");
                    nameList.add("Carwyn Garrison");
                    nameList.add("Mohammod Wynn");
                    nameList.add("Prisha Barton");
                    nameList.add("Riley-Jay Duran");
                    nameList.add("Nur Fox");
                    nameList.add("Alanah Gentry");
                    nameList.add("Margot Mcleod");
                    nameList.add("Savannah Humphreys");
                    nameList.add("Danyal Montes");
                    nameList.add("Ritik Bolton");
                    nameList.add("Niamh Spencer");
                    nameList.add("Carrie Bird");
                    nameList.add("Santino Mack");
                    nameList.add("Mara Ballard");
                    nameList.add("Timur Joseph");
                    nameList.add("Bogdan Patterson");
                    nameList.add("Momina Hail");
                    nameList.add("Reece Prentice");
                    nameList.add("Lesley Whitaker");
                    nameList.add("Alexia Esquivel");
                    nameList.add("Selena Marsh");
                    nameList.add("Darsh Webber");
                    nameList.add("Jamal Dunkley");
                    nameList.add("Aila Huang");
                    nameList.add("Cherise Fields");
                    nameList.add("Riccardo Trevino");
                    nameList.add("Anisa Diaz");
                    nameList.add("Diane Rigby");
                    nameList.add("Zaki Doherty");
                    nameList.add("Zoya Edwards");
                    nameList.add("Hughie Roth");
                    nameList.add("Jaden Bell");
                    nameList.add("Krystian Bush");
                    nameList.add("Miranda Kirkland");
                    nameList.add("Anne Sharples");
                    nameList.add("Tamia Burnett");
                    nameList.add("Adelina Luna");
                    nameList.add("Ivy Nolan");
                    nameList.add("Betty Figueroa");
                    nameList.add("Kaila Garrison");
                    nameList.add("Sufyaan Chadwick");
                    nameList.add("Nahla Sheldon");
                    nameList.add("Christiana Woodard");
                    nameList.add("Jon Velazquez");
                    nameList.add("Bea Phillips");
                    nameList.add("Aniya Dillard");
                    nameList.add("Arianne Wooten");
                    nameList.add("Rahul Mckeown");
                    nameList.add("Sasha Mackay");
                    nameList.add("Sade Whyte");
                    nameList.add("Sophia Reeve");
                    nameList.add("Luciano Chavez");
                    nameList.add("Clarence Goulding");
                    nameList.add("Holli Moore");
                    nameList.add("Barney Lindsey");
                    nameList.add("Bridie Brewer");
                    nameList.add("Kristi Forrest");
                    nameList.add("Buddy Mueller");
                    nameList.add("Mayur Lowery");
                    nameList.add("Junaid Aguilar");
                    nameList.add("Charis Houghton");
                    nameList.add("Kuba Clarke");
                    nameList.add("Tashan Hollis");
                    nameList.add("Reo Odling");
                    nameList.add("Dua Hussain");
                    nameList.add("Zakary Stein");
                    nameList.add("Bonnie Robles");
                    nameList.add("Tymoteusz Jarvis");
                    nameList.add("Tarun Doyle");
                    nameList.add("Rehaan Schwartz");
                    nameList.add("Maya Beattie");
                    nameList.add("Kajol Kavanagh");
                    nameList.add("Avaya Lynn");
                    nameList.add("Linzi Soto");
                    nameList.add("Aamir Wainwright");
                    nameList.add("Evelyn Keenan");
                    nameList.add("Iona Mcgregor");
                    nameList.add("Anish Flores");
                    nameList.add("Orla Mcnally");
                    nameList.add("Ellouise Reeves");
                    nameList.add("Phoenix Oneil");
                    nameList.add("Monet Medrano");
                    nameList.add("Sidney Pena");
                    nameList.add("Macaulay Frost");
                    nameList.add("Conna Daniels");
                    nameList.add("Leyton Mccartney");
                    nameList.add("Rida Reese");
                    nameList.add("Kit Brown");
                    nameList.add("Aurora Maxwell");
                    nameList.add("Faris Rawlings");
                    nameList.add("Fergus Pollard");
                    nameList.add("Olly Guevara");
                    nameList.add("Lyndsey Cannon");
                    nameList.add("Tyler-James Reilly");
                    nameList.add("John Mcghee");
                    nameList.add("Hubert Johns");
                    nameList.add("Zachariah Liu");
                    nameList.add("Anwar O'Doherty");
                    nameList.add("Patrik Shepard");
                    nameList.add("Chaya Burgess");
                    nameList.add("Tiago Povey");
                    nameList.add("Tahlia Neville");
                    nameList.add("Rimsha Britt");
                    nameList.add("Demi-Leigh Clay");
                    nameList.add("Milton Baxter");
                    nameList.add("Timur Robinson");
                    nameList.add("Ameena Hogg");
                    nameList.add("Kasey Seymour");
                    nameList.add("Santino Mullins");
                    nameList.add("Willard Dorsey");
                    nameList.add("Sama Marin");
                    nameList.add("Stephanie Gaines");
                    nameList.add("Laurence Hood");
                    nameList.add("Zackery Everett");
                    nameList.add("Jaya Allman");
                    updateDB(nameList);
                }
            } catch (IOException e) {
                throw new NameException(" ☹ OOPS!!! Unable to create database.");
            }
        }
    }

    /**
     * Updates the database with the given list of names.
     **/
    public static void updateDB(ArrayList<String> nameList) throws NameException {
        try {
            FileWriter fw = new FileWriter(String.valueOf(filePath));
            for (int i = 0; i < nameList.size(); i++) {
                String name = nameList.get(i);
                //String toWrite = "";
                fw.write(name + System.lineSeparator());
            }
            fw.close();
        } catch (IOException e) {
            throw new NameException(" ☹ OOPS!!! Unable to create database.");
        }
    }
}
