@startuml
title When User First Enter FinanceTools
actor User

User -> ":FinanceTools" : FinanceTools.main()
activate ":FinanceTools"

":FinanceTools" -> ":FileStorage" : readFileContents()
activate ":FileStorage"

":FileStorage" -> ":FinanceTools" : ArrayList Updated
deactivate ":FileStorage"

":FinanceTools" -> User : Information Up-to-date
deactivate ":FinanceTools"
@enduml