@startuml
title When User Stores Information
actor User

User -> ":FinanceTools" : handleStorage()
activate ":FinanceTools"

":FinanceTools" -> ":Storage" : handleInfoStorage()
activate ":Storage"

":Storage" -> ":FileStorage" : updateFile()
activate ":FileStorage"

":FileStorage" -> ":Storage" : File Updated
destroy ":FileStorage"

":Storage" -> ":FinanceTools" : Storage Updated
destroy ":Storage"

":FinanceTools" -> User : Information Updated
deactivate ":FinanceTools"
@enduml