@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Step 2

package EventList0 {
    class State1 as "Event \narduino course 30 Dec 2020 8pm []"
}

package EventList1 {
    class State3 as "Event \narduino course 30 Dec 2020 8pm [Harry Potter]"
}

package EventList2 {
    class State4 as "Event \narduino course 30 Dec 2020 8pm []"
}

package MemberList0 {
    class State2 as "Member \nHarry Potter 88888888 qaz@gmail.com president"
}

EventList0 -->EventList1
EventList1 -->EventList2
MemberList0 -->EventList1

hide EventList1
hide EventList2

@enduml