@startuml
backend -> AddCommand: execute()


activate AddCommand
AddCommand -> EventList: addEvent()
activate EventList
EventList -> Event: add()
activate Event
EventList --> Event : printEvent()
deactivate EventList
deactivate Event
deactivate AddCommand

@enduml