@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Step 3

package EventList0 {
    class State1 as " "
}
package EventList1 {
    class State2 as "Event \narduino course 30 Dec 2020 8pm"
}

package EventList2 {
    class State3 as " "
}

EventList0 -left->EventList1
EventList1 -left->EventList2


class Pointer as "Current State" #FFFFF
Pointer -up-> EventList2


@endum