@startuml
!include styleHR.puml

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After Step 2

package MemberList {
    class State1 as "__John Sterling:Member__"
}

class Pointer as "Current State" #FFFFF
Pointer -up-> State1
@enduml