@startuml
!include styleHR.puml

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After Step 1

package MemberList {
    class State0 as "__John Sterling:Member__"
    class State1 as "__Harry Potter:Member__"
}

@enduml