@startuml
!include styleHR.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Step 2 state

package MemberList {
    class State1 as "Member\nHarry Potter\n88888888\nqaz@gmail.com\npresident"
    class State2 as "Member\nJohn Sterling\n12345678\n123@gmail.com\nmember"
}

Search -up->State2


@enduml