@startuml

 -> ":CommandDelMember": execute()
activate ":CommandDelMember"
activate ":MemberList"
activate ":MemberList" #DarkSalmon
":CommandDelMember" -> ":MemberList" : deleteFromList()
activate ":MemberList"
":MemberList" -> ":Member" : toString()
activate ":Member"
":Member" --> ":MemberList" : updateAttendanceRate()
":MemberList" --> ":MemberList" : calculateAttendanceRate()
return output
":MemberList" -> ":Member": remove()
activate ":Member"
return output
return output
return output

@enduml