@startuml

 -> ":CommandChangeMemberInfo": execute()
activate ":CommandChangeMemberInfo"

":CommandChangeMemberInfo" -> ":MemberList" : findMemberByName()
activate ":MemberList"
":MemberList" --> ":CommandChangeMemberInfo"
deactivate ":MemberList"
":CommandChangeMemberInfo" -> ":MemberList" : changeMemberInfo()
activate ":MemberList"
":MemberList" -> ":Member" : toString()
activate ":Member"
ref over ":Member", ":MemberList"
    updateEventAttendance
end ref
return output
return output
return output

@enduml