@startuml
 -> ":CommandAddMember": execute()


activate ":CommandAddMember"
":CommandAddMember" -> ":MemberList" : addToList()
activate ":MemberList"
":MemberList" -> ":Member": add()
activate ":Member"
return
":MemberList" -> ":Member" : toString()
activate ":Member"
ref over ":Member", ":MemberList"
    updateEventAttendance
end ref
return output
return output
<-- ":CommandAddMember" : output
deactivate ":CommandAddMember"
@enduml