@startuml
 -> ":CommandAddMember": execute()


activate ":CommandAddMember"
":CommandAddMember" -> ":MemberList" : addToList()
activate ":MemberList"
":MemberList" -> ":Member": add()
activate ":Member"
return
":MemberList" -> ":Member" : toString()
activate ":Member"
return
return output
return output
deactivate ":CommandAddMember"
@enduml