@startuml

 -> ":CommandDelMember": execute()
activate ":CommandDelMember"
activate ":MemberList"
":CommandDelMember" -> ":MemberList" : deleteFromList()
activate ":MemberList"
":MemberList" -> ":Member" : toString()
activate ":Member"
ref over ":Member", ":MemberList"
    updateEventAttendance
end ref
return output

ref over ":MemberList", ":Member", ":EventList", ":Event"
    deleteFromEvents
end ref

":MemberList" -> ":Member": remove()
activate ":Member"
return output
return output
deactivate ":MemberList"
<-- ":CommandDelMember" : output
deactivate ":CommandDelMember"
@enduml