@startuml
participant ":CommandListConnection" as CommandFinanceSummary
participant ":MemberList" as FinanceList
->CommandFinanceSummary:execute()
activate CommandFinanceSummary
CommandFinanceSummary -> FinanceList : searchConnection()
activate FinanceList
loop numOfMembers
FinanceList -> FinanceList: searcheRole()
end
return output
return output
@enduml