@startuml

 -> ":CommandDelMember": execute()
activate ":CommandDelMember"
activate ":MemberList"
":CommandDelMember" -> ":MemberList" : deleteFromList(index)
activate ":MemberList"
":MemberList" -> ":Member" : toString()
activate ":Member"
ref over ":Member", ":MemberList"
    updateEventAttendance(memberName)
end ref
return output


ref over ":MemberList", ":Member", ":EventList", ":Event"
    deleteFromEvents(memberName)
end ref
":MemberList" -> ":Member" !!
return output
deactivate ":MemberList"
<-- ":CommandDelMember" : output
deactivate ":CommandDelMember"
@enduml