@startuml
-> ":MemberList" : deleteFromEvents(memberName)
activate ":MemberList"
loop eventSize
":MemberList" -> ":EventList"
activate ":EventList"
":EventList" -> ":Event" :getEventName()
activate ":Event"
":Event" --> ":EventList"
deactivate ":Event"
":EventList" --> ":MemberList" : eventName
deactivate ":EventList"
":MemberList" -> ":EventList" : deleteAttendance(eventName, memberName)
ref over ":MemberList", ":EventList", ":Event"
deleteAttendance(eventName, memberName)
end ref
activate ":EventList"
":EventList" --> ":MemberList"
deactivate ":EventList"
end
<-- ":MemberList"
deactivate ":MemberList"
@enduml