@startuml
autoactivate on
actor User

"User" -> ":Handler": Input command in FinanceTools.main()
":Handler" ->":Handler": handleAccountStorage(packet, filePath, infoText)

   ":Handler"-> ":AccountStorage" : handlePacket(packet)

        == Handling of Params in packet ==
        ":AccountStorage" -> ":AccountStorage" : handleParams
            ":AccountStorage" -> ":ParamChecker" : setPacket(packet)
            return
            loop For all paramType in the command packet
                note left: "Note: Params will be verified for correctness\nby ParamChecker singleton class before being\nset into the entry instance."
                ":AccountStorage" -> ":AccountStorage" : handleSingleParam
                    alt "paramType = /n"
                        ":AccountStorage" -> ":AccountStorage" : getParam(paramType)
                        return
                    else "paramType = /ir"
                        ":AccountStorage" ->":ParamChecker": checkAndReturnDoubleSignedSigned(paramType)
                        return amount
                        ":AccountStorage" -> ":AccountStorage" : getParam(paramType)
                        return
                    else "paramType = /r"
                        ":AccountStorage" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":AccountStorage" -> ":AccountStorage" : getParam(paramType)
                        return
                    else "paramType = /c"
                        ":AccountStorage" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":AccountStorage" -> ":AccountStorage" : getParam(paramType)
                        return
                    else "paramType = /o"
                        ":AccountStorage" -> ":AccountStorage" : getParam(paramType)
                        return
                    else "paramType = /rm"
                        ":AccountStorage" ->":ParamChecker": checkAndReturnIntSigned(paramType)
                        return amount
                        ":AccountStorage" -> ":AccountStorage" : getParam(paramType)
                        return
                    end
                return
            end
        return

return state


box "Logic" #LightBlue
participant ":AccountStorage"
participant ":ParamChecker"
endBox
@enduml