@startuml
hide circle
skinparam classAttributeIconSize 0
class "{abstract} \nHandler" {
 +handleMilesCredit(:CommandPacket)
}

class MilesCredit {
 +calculateMiles()
}

"{abstract} \nHandler" --> MilesCredit : Calculates miles
@enduml