@startuml
autoactivate on
actor User

"User" -> ":Handler": Input command in FinanceTools.main()
":Handler" ->":Handler": handleMilesCredit(packet)

   ":Handler"-> ":MilesCredit" : handlePacket(packet)

        == Handling of Params in packet ==
        ":MilesCredit" -> ":MilesCredit" : handleParams
            ":MilesCredit" -> ":ParamChecker" : setPacket(packet)
            return
            loop For all paramType in the command packet
                note left: "Note: Params will be verified for correctness\nby ParamChecker singleton class before being\nset into the entry instance."
                ":MilesCredit" -> ":MilesCredit" : handleSingleParam
                    alt "paramType = /a"
                        ":MilesCredit" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":MilesCredit" -> ":MilesCredit" : getParam(paramType)
                        return
                    else "paramType = /r"
                        ":MilesCredit" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":MilesCredit" -> ":MilesCredit" : getParam(paramType)
                        return
                    end
                return
            end
        return

return state


box "Logic" #LightBlue
participant ":MilesCredit"
participant ":ParamChecker"
endBox
@enduml