@startuml
title Monthly Compound Interest Calculator
autoactivate on
actor User

"User" ->  ":Handler": Input command in FinanceTools.main()
":Handler" -> ":Handler": handleMonthlyCommpoundInterest(packet)

   ":Handler"-> ":MonthlyCompoundInterest" : handlePacket(packet)

        == Handling of Params in packet ==
        ":MonthlyCompoundInterest" -> ":MonthlyCompoundInterest" : handleParams
            ":MonthlyCompoundInterest" -> ":ParamChecker" : setPacket(packet)
            return
            loop For all paramType in the command packet
                note left: "Note: Params will be verified for correctness\nby ParamChecker singleton class before being\nset into the entry instance."
                ":MonthlyCompoundInterest" -> ":MonthlyCompoundInterest" : handleSingleParam
                    alt "paramType = /a"
                        ":MonthlyCompoundInterest" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":MonthlyCompoundInterest" -> ":MonthlyCompoundInterest" : getParam(paramType)
                        return
                    else "paramType = /r"
                        ":MonthlyCompoundInterest" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":MonthlyCompoundInterest" -> ":MonthlyCompoundInterest" : getParam(paramType)
                        return
                    else "paramType = /p"
                        ":MonthlyCompoundInterest" ->":ParamChecker": checkAndReturnIntSigned(paramType)
                        return amount
                        ":MonthlyCompoundInterest" -> ":MonthlyCompoundInterest" : getParam(paramType)
                        return
                    else "paramType = /d"
                        ":MonthlyCompoundInterest" ->":ParamChecker": checkAndReturnDoubleSigned(paramType)
                        return amount
                        ":MonthlyCompoundInterest" -> ":MonthlyCompoundInterest" : getParam(paramType)
                        return
                    end
                return
            end
        return

return state

deactivate User


box "Logic" #LightBlue
participant ":MonthlyCompoundInterest"
participant ":ParamChecker"
endBox
@enduml