@startuml
actor user
participant ":Duke"
box logic #LightBlue
participant ":Parser"
participant ":AddFavCommand"
end box
box model #A9DFDF
participant ":FavList"
participant ":Fav"
end box
box Ui #A9D1D0
participant "<<class>>\n:Ui"
end box

user ->":Duke"
activate ":Duke"
":Duke" -> ":Parser" : /addfav
activate ":Parser"
create ":AddFavCommand"
":Parser" -> ":AddFavCommand"
activate ":AddFavCommand"
":AddFavCommand" --> ":Parser"
deactivate ":AddFavCommand"
":Parser" -> ":AddFavCommand" : executeCommand()
activate ":AddFavCommand"
opt null command
    ":AddFavCommand" --> ":Parser"
    ":Parser" --> ":Duke"
end
":AddFavCommand" -> ":AddFavCommand" : createFav()
activate ":AddFavCommand"

'alt description empty
'    create ":Fav"
'    ":AddFavCommand" -> ":Fav" : new Fav(command, command)
'     activate ":Fav"
'    ":Fav" --> ":AddFavCommand"
'    deactivate ":Fav"
'else description not empty
'    create ":Fav"
'    ":AddFavCommand" -> ":Fav" : new Fav(command, desc)
'     activate ":Fav"
'    ":Fav" --> ":AddFavCommand"
'    deactivate ":Fav"
'end

":AddFavCommand" --> ":AddFavCommand"
deactivate ":AddFavCommand"
":AddFavCommand" -> ":FavList" : contains(Fav)
activate ":FavList"

loop size of FavList times
    ":FavList" -> ":Fav" : equals()
     activate ":Fav" 
    ":Fav" --> ":FavList"
    deactivate ":Fav" 
end

":FavList" --> ":AddFavCommand"
deactivate ":FavList"
opt no duplicate Fav
    ":AddFavCommand" -> ":FavList" : addFav()
    activate ":FavList"
    ":FavList" --> ":AddFavCommand"
    deactivate ":FavList"
    ":AddFavCommand" -> "<<class>>\n:Ui" : addFavMessage()
    activate "<<class>>\n:Ui"
    "<<class>>\n:Ui" --> ":AddFavCommand"
    deactivate "<<class>>\n:Ui"
    ":AddFavCommand" --> ":Parser"
    deactivate ":AddFavCommand"
    ":Parser" --> ":Duke"
    deactivate ":Parser"
    ":Duke" --> user
    deactivate ":Duke"

@enduml