@startuml

skinparam BoxPadding 20
participant ":Duke"
box logic #LightBlue
participant ":Parser"
participant ":RouteMapCommand"
end box
box model #A9DFDF
participant "<<class>>\n:BusData"
participant ":Bus"
end box
box Ui #A9D1D0
participant ":Ui"
end box


":Duke" -> ":Ui" : getUserInput()
activate ":Duke"
activate ":Ui"
":Ui" --> ":Parser": String userInput
deactivate ":Ui"

activate ":Parser"
create ":RouteMapCommand"
":Parser" -> ":RouteMapCommand" :extractType()
activate ":RouteMapCommand"
":RouteMapCommand" --> ":Parser"
deactivate ":RouteMapCommand"
":Parser" -> ":RouteMapCommand" : executeCommand()
activate ":RouteMapCommand"
":RouteMapCommand" -> "<<class>>\n:BusData" : selectBus();
activate "<<class>>\n:BusData"
loop number of bus routes
    "<<class>>\n:BusData" -> ":Bus" : equals()
     activate ":Bus"
    ":Bus" --> "<<class>>\n:BusData" : Bus object
    deactivate ":Bus"
end

alt Bus object found
"<<class>>\n:BusData" --> ":RouteMapCommand" : Bus object
else Bus object not found
"<<class>>\n:BusData" --> ":RouteMapCommand" : null
deactivate "<<class>>\n:BusData"
end
":RouteMapCommand" -> ":Ui" : printFullRoute()
activate ":Ui"
":Ui" --> ":RouteMapCommand"
deactivate ":Ui"

":RouteMapCommand" --> ":Parser"
deactivate ":RouteMapCommand"
":Parser" --> ":Duke":Boolean isOngoing
deactivate ":Parser"


@enduml