@startuml

start

partition UserCallCommand {
      :edit friends;
  }

#lightblue:Program Output:
Input the detail of the show you want to change;

partition UserInteraction {


   repeat
   :User input;
   split
    :name|
   split again
    :episode|
   split again
    :season|
   split again
    : duration|

    split again
    : done|
   end split
   #lightblue: show data updated;
   repeat while (input != done)
   :done ;
  }

#lightblue:Program Output:
updated successfully;
stop
@enduml