@startuml

class Duke
class Storage
interface SaveState
class WatchTime
class ShowList

Duke "1" *--> "1" Storage
Storage ..|> SaveState
Duke "1" *--> "1" WatchTime
Storage --> "0..1" WatchTime
Duke "1" *--> "1" ShowList
Storage --> "0..1" ShowList

class ShowList {
+ {static} showList:HashMap<String,Show>
+ ShowList():void
}
class WatchTime {
-recordedDate:LocalDate
-durationWatchedToday:int
-dailyWatchLimit:int
+ WatchTime(:LocalDate,:int,:int):void
+ saveStateFormat():String
}

interface SaveState {
+saveState():void
+loadState():ShowList
}

class Storage {
-filePath:String
-recordedDate:LocalDate
-durationWatchedToday:int
-dailyWatchLimit:int
+Storage(:String):void
+saveState():void
+loadState():void
-loadWatchTimeDetail(:Scanner):WatchTime
}

class Duke{
-shows:ShowList
-storage:Storage
-watchTime:watchTime
}
@enduml