@startuml
!include style.puml
show member
skinparam arrowThickness 1.1

Class "{abstract}\nCommand" as Command LOGIC_COLOR {
    + {abstract} execute(ui : Ui, access : Access, storage : Storage) : void
}
Class "{abstract}\nAddCommand" as AddCommand LOGIC_COLOR {
    + {abstract} execute(ui : Ui, access : Access, storage : Storage) : void
    + prepareResult(type : String, content : String, count : int) : String
}
Class AddCardCommand LOGIC_COLOR {
    + AddCardCommand(question : String, answer : String)
    + execute(ui : Ui, access : Access, storage : Storage) : void
    - addCard(access : Access, storage : Storage) : String
}

Class Card MODEL_COLOR {
    - question : String
    - answer : String
    + Card(question : String, answer : String)
}
Class Access MODEL_COLOR {
    + getChapter() : Chapter
}
Class Chapter MODEL_COLOR {
    + getCards() : CardList
}
Class CardList MODEL_COLOR {
    + addCard(card : Card) : void
    + checkCardExistence(newQuestion : String,
    newAnswer : String) : boolean
    + getCardCount() : int
}

Class Storage STORAGE_COLOR {
    + saveCards(cards: CardList,
    module : String, chapter : String) : void
}

Class Ui UI_COLOR {
    + showToUser(message : String) : void
}

AddCommand -up[LOGIC_COLOR_T4]-|> Command
AddCardCommand -up[LOGIC_COLOR_T4]-|> AddCommand

AddCardCommand -left[LOGIC_COLOR_T4]-> "0..1" Card
AddCardCommand .down[LOGIC_COLOR_T4].> Access
AddCardCommand .down[LOGIC_COLOR_T4].> Storage
AddCardCommand .down[LOGIC_COLOR_T4].> Ui

Access -left[MODEL_COLOR_T4]-> " 0..1 " Chapter

Chapter *-up[MODEL_COLOR_T4]-> " 0..1 " CardList
CardList *-up[MODEL_COLOR_T4]-> " * " Card

AddCardCommand .down[LOGIC_COLOR_T4].> Chapter
AddCardCommand .left[LOGIC_COLOR_T4].> CardList

@enduml
