@startuml

!include style.puml
show member
skinparam arrowThickness 1.1

Class "{abstract} \n Command" as Command LOGIC_COLOR {
    + {abstract} execute(ui : Ui, access : Access,
    storage : Storage) : void
}

Class "{abstract} \n BackCommand" as BackCommand LOGIC_COLOR {
    + {abstract} execute(ui : Ui, access : Access,
    storage : Storage) : void
}

Class "BackAdminCommand" as BackAdminCommand LOGIC_COLOR {
    + execute(ui : Ui , access : Access, storage : Storage) : void
}

Class "Scheduler" as Scheduler LOGIC_COLOR {

}

Class "Access" as Access MODEL_COLOR {
    # moduleLevel : String
    + setModuleLevel(moduleLevel : String) : void
    + setBackAdminLevel(moduleLevel : String) : void
    + setIsAdminLevel() : void
}

BackCommand -left[LOGIC_COLOR_T4]-|> Command
BackAdminCommand -up[LOGIC_COLOR_T4]-|> BackCommand
BackAdminCommand .left[LOGIC_COLOR_T4].> Access

@enduml