@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor COMMON_COLOR_T4
skinparam classBackgroundColor COMMON_COLOR

package Common {
    Class KajiLog
    Class Message
}

package Logic {
    Class HiddenLogic #FFFFFF
}

package Ui {
    Class HiddenUi #FFFFFF
}

package Model {
    Class HiddenModel #FFFFFF
}

Logic .left.> Message
Ui .up.> Message
Model .down.> Message
Logic .left.> KajiLog
Ui .up.> KajiLog
Model .down.> KajiLog

@enduml