@startuml

!include style.puml
show member
skinparam arrowThickness 1.1

Class "{abstract} \n Command" as Command LOGIC_COLOR {
    + {abstract} execute(ui : Ui, access : Access,
    storage : Storage) : void
}

Class Ui UI_COLOR {
    + printDueByTodayMessage(int listSize, String commandType) : void
    + printDueChapters(dueDueChapters : ArrayList<DueChapter>) : void
}

Class Storage STORAGE_COLOR {
    + loadAllDueChapters() : ArrayList<DueChapter>
}

Class StorageLoad STORAGE_COLOR {
    + loadAllDueChapters() : ArrayList<DueChapter>
    + loadAllChaptersAsDueChapters() : ArrayList<DueChapter>
}

Class "ListDueCommand" as ListDueCommand LOGIC_COLOR {
    - allDueChapters : ArrayList<DueChapter>
    - dueDueChapters : ArrayList<DueChapter>
    + execute(ui : Ui , access : Access, storage : Storage) : void
    - loadAllDueChapters(storage : Storage, ui : Ui) :void
    - addIfDue(chapter : DueChapter, deadline : LocalDate) : void
    - setDueDueChapters() : void
}

Class "Scheduler" as Scheduler LOGIC_COLOR {
    - isDeadlineDue(dueby : LocalDate) : boolean
}

ListDueCommand -left[LOGIC_COLOR_T4]-|> Command
ListDueCommand .right[LOGIC_COLOR_T4].> Scheduler
ListDueCommand .down[LOGIC_COLOR_T4].> Storage
Storage .left[LOGIC_COLOR_T4].> StorageLoad
ListDueCommand .up[LOGIC_COLOR_T4].> Ui

@enduml