@startuml
-> ":RemoveCardCommand" : execute(ui, access, storage)
activate ":RemoveCardCommand"
":RemoveCardCommand" -> ":RemoveCardCommand" : removeCard(access, storage)
activate ":RemoveCardCommand"
":RemoveCardCommand" -> ":Access" : getChapter()
":RemoveChapterCommand" <-- ":Access"
destroy ":Access"
":RemoveCardCommand" -> ":Chapter" : getCards()
":RemoveCardCommand" <-- ":Chapter" : cards
destroy ":Chapter"
":RemoveCardCommand" -> ":CardList" : getAllCards()
":RemoveCardCommand" <-- ":CardList" : allCards
destroy ":CardList"
":RemoveCardCommand" -> ":Storage" : saveCards(cards, module, chapter)
destroy ":Storage"
":RemoveCardCommand" -> ":RemoveCommand" : prepareResult(type, card, count)
":RemoveCardCommand" <-- ":RemoveCommand" : result
destroy ":RemoveCommand"
":RemoveCardCommand" --> ":RemoveCardCommand" : result
deactivate ":RemoveCardCommand"
":RemoveCardCommand" -> ":Ui" : showToUser(result)
destroy ":Ui"
<-- ":RemoveCardCommand"
deactivate ":RemoveCardCommand"
@enduml