@startuml

!include style.puml
show member
skinparam arrowThickness 1.1

Class "{abstract} \n Command" as Command LOGIC_COLOR {
  + {abstract} execute(ui : Ui, access : Access,
  storage : Storage) : void
}

Class "{abstract} \n RemoveCommand" as RemoveCommand LOGIC_COLOR {
  + {abstract} execute(ui : Ui, access : Access,
  storage : Storage) : void
  # prepareResult(type : String, content : String,
  count : int) : String
}

Class "RemoveCardCommand" as RemoveCardCommand LOGIC_COLOR {
    + RemoveCardCommand(removeIndex : int)
    - removeIndex : int
    + execute(ui : Ui , access : Access, storage : Storage) : void
    - removeCard(access Access, storage Storage) : String
}

Class "Access" as Access MODEL_COLOR {
    + getChapter() : Chapter
}

Class "Chapter" as Chapter MODEL_COLOR {
    + getCards() : CardList
}

Class "CardList" as CardList MODEL_COLOR {
    + getAllCards(): ArrayList<Card>
    + removeCard(removeIndex : int) : void
}

Class "Ui" as Ui UI_COLOR {
    + showToUser(message : String) : void
}

Class "Storage" as Storage STORAGE_COLOR {
    + saveCards(card : CardList, module : String, chapter : String)
}

RemoveCommand -left[LOGIC_COLOR_T4]-|> Command
RemoveCardCommand -up[LOGIC_COLOR_T4]-|> RemoveCommand
RemoveCardCommand .down[LOGIC_COLOR_T4].> Storage
RemoveCardCommand .left[LOGIC_COLOR_T4].> Ui
RemoveCardCommand .up[LOGIC_COLOR_T4].> Access
RemoveCardCommand .right[LOGIC_COLOR_T4].> Chapter
RemoveCardCommand .right[LOGIC_COLOR_T4].> CardList
Access *-down[MODEL_COLOR]-> "    0..1" Chapter
Chapter *-down[MODEL_COLOR]-> "   0..1" CardList
Storage -right[HIDDEN]-> CardList

@enduml