@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":ReviseCommand" as ReviseCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Chapter" as Chapter MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR
end box

activate ReviseCommand
ReviseCommand -> ReviseCommand : getCards(ui, access, storage)
activate ReviseCommand
ReviseCommand -> Storage : loadCard(module, chapter)
activate Storage
ReviseCommand <-- Storage
deactivate Storage
ReviseCommand <-- Storage : allCards
ReviseCommand -> Chapter : setCards(allCards)
activate Chapter
ReviseCommand <-- Chapter
deactivate Chapter
ReviseCommand --> ReviseCommand : allCards
deactivate ReviseCommand

@enduml