@startuml

hide circle
skinparam classAttributeIconSize 0

class "{abstract} \n Command"{
  + isExist() : String {abstract}
  + execute() : void {abstract}
}

class "Kaji" {
    + run() : void
}

class "Access" {
    + getChapter() : Chapter
}

class "CardList" {
    + getAllCards() : ArrayList<Card>
}

class "Ui" {
    + showToUser(String) : void
}

class "Chapter" {
    - cards : CardList
    + getCards() : CardList
}

class "Card" {
    - rating : int
    + getRating() : int
}

"{abstract} \n Command" <|-- ShowRateCommand
ShowRateCommand : - easyPercentage : Double
ShowRateCommand : - mediumPercentage : Double
ShowRateCommand : - hardPercentage : Double
ShowRateCommand : - cannotAnswerPercentage : Double
ShowRateCommand : - computePercentage(Chapter, Ui) : int
ShowRateCommand : + isExist() : void

Kaji *- "{abstract} \n Command"

ShowRateCommand ..> Access
Access ..> "1" Chapter
Chapter ..> "1" CardList
CardList ..> "*" Card
ShowRateCommand ..> Ui

@enduml