@startuml
!include style.puml
show member
skinparam arrowThickness 1.1

class "{abstract} \n Command" as Command LOGIC_COLOR {
    + {abstract} isExist() : String
    + {abstract} execute(ui : Ui, access : Access, storage : Storage) : void
}

class "Access" MODEL_COLOR {
    + getChapter() : Chapter
}

class "CardList" MODEL_COLOR {
    + getAllCards() : ArrayList<Card>
}

class "Ui" UI_COLOR {
    + showToUser(String) : void
}

class "Chapter" MODEL_COLOR {
    - cards : CardList
    + getCards() : CardList
}

class "Card" MODEL_COLOR {
    - rating : int
    + getRating() : int
}

class ShowRateCommand LOGIC_COLOR {
    - easyPercentage : Double
    - mediumPercentage : Double
    - hardPercentage : Double
    - cannotAnswerPercentage : Double
    - computePercentage(Chapter, Ui) : int
    + isExist() : void
}

Command <|-right[LOGIC_COLOR_T4]- ShowRateCommand

ShowRateCommand .down[LOGIC_COLOR_T4].> Access
Access -down[MODEL_COLOR_T4]-> "1" Chapter
Chapter -left[MODEL_COLOR_T4]-> "1" CardList
CardList -left[MODEL_COLOR_T4]-> "*" Card
ShowRateCommand .up[LOGIC_COLOR_T4].> Ui

@enduml