@startuml

!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class HiddenOutside #FFFFFF

package logic {
    Class HiddenModel #FFFFFF
}

package storage {

    Class Storage STORAGE_COLOR
    Class StorageLoad STORAGE_COLOR
    Class StorageParser STORAGE_COLOR
    Class StorageWrite STORAGE_COLOR
}

logic .down.> Storage
HiddenOutside .up.> Storage

Storage .right.> StorageLoad
StorageLoad .left.> Storage
Storage .up.> StorageWrite
StorageWrite .down.> Storage

StorageLoad .down.> StorageParser

@enduml