@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

Class Kaji LOGIC_COLOR

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Storage <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Ui <<Rectangle>> {
Class Ui UI_COLOR
}

Kaji .up.> Ui
Model -up-> Ui
Storage -up-> Ui
Logic -up-> Ui

Storage -[hidden]left- Model
Model -[hidden]left- Logic
Logic -[hidden]left- Kaji

@enduml