@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 50
skinparam shadowing false
left to right direction

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

rectangle Storage {
}





rectangle Model {
rectangle Data {

    class Ledger {

    }

    class Entry {

    }



    }
    rectangle DataList {



        class LedgerList {

        }

        class EntryList {

        }

    }


}

    LedgerList --> "*" Ledger #line:red;text:red  : contains >
    EntryList --> "*" Entry #line:red;text:red : contains >

rectangle "LogicManagers" {
    class GoalTracker {
    }

    class ManualTracker {

    }

    class EntryTracker {

    }
}


Ledger *-> EntryList #line:blue;text:blue : > Maintains
EntryTracker o-> "1" EntryList #line:red;text:red : stores \nentries \nwith >
ManualTracker *-> "1" LedgerList #line:red;text:red : stores \nledgers \nwith >

GoalTracker ----> Entry #line:red;text:red : Tracks against \n input goal >
GoalTracker ..> EntryTracker #line:red;text:red : Displays\ngoal\nprogress >

Storage ..> LedgerList #line:red;text:red : Saves and \nLoads DataList >
Storage ..> EntryList #line:red;text:red : Saves and \nLoads \nDataList >

@enduml