@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 20
skinparam shadowing false

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

rectangle "LogicManagers" {
    class ManualTracker {
        ~ {static} handleCreateLedger() : State
        ~ {static} handleOpenLedger() : State
        ~ {static} handleDeleteLedger() : State
    }

    class EntryTracker {
        ~ {static} handleCreateEntry() : State
        ~ {static} handleEditEntry() : State
        ~ {static} handleDeleteEntry() : State
    }
}

rectangle "CommandHandlers" {
    rectangle LedgerHandlers {
        class createLedgerHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : HandlerPacket) : void
        }
        class retrieveLedgerHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : HandlerPacket) : void
        }
        ManualTracker --> createLedgerHandler
        ManualTracker --> retrieveLedgerHandler
    }

    rectangle EntryHandlers {
        class createEntryHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : HandlerPacket) : void
        }
        class editEntryHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : HandlerPacket) : void
        }
        class retrieveEntryHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : HandlerPacket) : void
        }
        EntryTracker --> createEntryHandler
        EntryTracker --> retrieveEntryHandler
        EntryTracker --> editEntryHandler

    }
}

@enduml