@startuml
left to right direction
hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 20
skinparam shadowing false
skinparam linetype ortho
skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

rectangle Logic {



    package p2 <<Layout>> {
    }

    class ParamChecker <<Singleton>>{
        + checkAndReturnDate(paramType : String) : LocalDate
        + checkAndReturnTime(paramType : String) : LocalTime
        + checkAndReturnIndex(paramType : String, list : ArrayList) : Integer
        + checkAndReturnDouble(paramType : String) : Double
        + checkAndReturnInt(paramType : String) : Integer
        + checkAndReturnCategory(paramType : String) : String
    }


rectangle CommandHandlers {
    abstract class "{abstract}\nParamHandler" {
        # paramChecker : ParamChecker
        # hasParsedAllParams : boolean
        + handleParams(packet : CommandPacket) : void
        + getHasParsedAllRequiredParams() : boolean
        + setRequiredParams(paramTypes : String...) : void
        # checkParamRequirementSatisfied(param : String) : boolean
        + {abstract} handleSingleParam(packet : CommandPacket, paramType : String)
    }

    rectangle "Ledger CommandHandlers" {
        class createLedgerCommand {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : CommandPacket) : void
        }
        class retrieveLedgerCommand {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : CommandPacket) : void
        }
    }

    rectangle XYZCommands {
    }



    rectangle "Entry CommandHandlers" {
        class createEntryCommand {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : CommandPacket) : void
        }
        class editEntryHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : CommandPacket) : void
        }
        class retrieveEntryHandler {
            + handlePacket() : void
            + handleSingleParams(paramType : String) : void
            + handleParams(packet : CommandPacket) : void
        }
        package p4 <<Layout>> {
        }

        package p5 <<Layout>> {
        }

        p4 -[hidden]- p5
        p5 -[hidden]- "{abstract}\nParamHandler"
    }




    ParamChecker "1" <.[norank]. createLedgerCommand #line:blue;text:black
    ParamChecker "1" <.[norank]. retrieveLedgerCommand #line:blue;text:black
    ParamChecker "1" <.[norank]. createEntryCommand #line:blue;text:black
    ParamChecker "1" <.[norank]. editEntryHandler #line:blue;text:black
    ParamChecker "1" <.[norank]. retrieveEntryHandler #line:blue;text:black
    ParamChecker "1" <.[norank]. XYZCommands #line:blue;text:black
    "{abstract}\nParamHandler" <|-[norank]- createLedgerCommand #line:purple;line.bold;text:red
    "{abstract}\nParamHandler" <|-[norank]- retrieveLedgerCommand #line:purple;line.bold;text:red
    "{abstract}\nParamHandler" <|-[norank]- createEntryCommand #line:purple;line.bold;text:red
    "{abstract}\nParamHandler" <|-[norank]- retrieveEntryHandler #line:purple;line.bold;text:red
    "{abstract}\nParamHandler" <|-[norank]- editEntryHandler #line:purple;line.bold;text:red
    "{abstract}\nParamHandler" <|-[norank]- XYZCommands #line:purple;line.bold;text:red

    note bottom of XYZCommands: Includes FinanceTools Calculator functions\n, RecurringEntry Commands, etc.
}

note right of ParamChecker: Contains methods that check validity of params supplied





@enduml