@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 50
skinparam shadowing false
left to right direction

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

rectangle "Storage Output" {
    rectangle "Save files in *.txt" {
    }
}


rectangle FinanceIt {

    rectangle InputManager {
    }

    rectangle LogicManager {
    }

    rectangle Storage {
    }

    rectangle Logic {
    }

    rectangle Model {
    }

    LogicManager <-- Model: Manipulates data \nrepresented in Model
    Storage <--- Model: Performs save and \nload operations
    LogicManager <... InputManager : Receives processed input
    LogicManager ...> Logic : Handles operation \ncontrol flow and logic
    Storage <.. "Storage Output" : Handles saving of \nprogram state \ninto text files

}
rectangle Person {
}

Person -> InputManager : Supply \ninput \nstring
FinanceIt -[hidden]right Person

@enduml