@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 100
skinparam shadowing false
left to right direction


skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}




rectangle Model {

}

rectangle InputManager {
}



rectangle LogicManagers {
    class ManualTracker {
    }
    
    class "       RecurringTracker         " {
    }

    class EntryTracker {
    }

    class GoalTracker {
    }

    class FinanceTools{
    }

    EntryTracker --> Model : stores entries with >
    ManualTracker --> Model : stores ledgers with >
    "       RecurringTracker         " ---> Model : stores RecurringEntries with >
}

ManualTracker --> InputManager : > Handles input 
EntryTracker --> InputManager : > Handles input 
"       RecurringTracker         " --> InputManager : > Handles input 

GoalTracker --> Model : Tracks against input goal >
GoalTracker <. EntryTracker :   \n         Provides\n      Entry \n             Information\n             to generate\n           Goal data >




@enduml