@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 100
skinparam shadowing false
left to right direction
scale 1049 width

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}




rectangle Model {

}

rectangle InputManager {
}



rectangle LogicManagers {
    class ManualTracker {
    }
    
    class "       RecurringTracker         " {
    }

    class EntryTracker {
    }

    class GoalTracker {
    }

    class FinanceTools{
    }

    EntryTracker --> Model : < stores entries of
    ManualTracker --> Model : < stores ledgers of
    "       RecurringTracker         " ---> Model : < stores RecurringEntries of
}

ManualTracker ..> InputManager : > Handles input with
EntryTracker ..> InputManager : > Handles input with
"       RecurringTracker         " ..> InputManager : > Handles input with
FinanceTools ..> InputManager : > Handles input with

GoalTracker --> Model : Tracks input goal with data from >
GoalTracker <. EntryTracker :   \n         Provides\n      Entry \n             Information\n             to generate\n           Goal data >




@enduml