@startuml

hide circle
skinparam classAttributeIconSize 0
skinparam BoxPadding 20
skinparam shadowing false

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

rectangle LogicManager{
}

rectangle Logic {


    class ParamChecker <<Singleton>>{

    }


rectangle CommandHandlers {

    class XYZCommandHandlers {
    }




    XYZCommandHandlers ..right> "1"  ParamChecker #line:blue;text:black : < Checks param validity for

    note top of XYZCommandHandlers: Includes FinanceTools Calculator functions\n, RecurringEntry Commands, etc.
}

LogicManager -> XYZCommandHandlers : < Performs param-dependent \noperations for
note top of ParamChecker: Contains methods that \ncheck validity of params supplied





@enduml